Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2019-07, with the labels that each got.

#97 Boundary2plus
  art/attacks/__init__.py
  art/attacks/hop_skip_jump.py
  notebooks/hopskipjump_attack.ipynb
  tests/attacks/test_hop_skip_jump.py
Labels: attack

#111 Update notebook attack_defense_imagenet
  notebooks/attack_defense_imagenet.ipynb
Labels: improvement

#119 Generalize classifiers from TF / Keras / PyTorch / MXNet to other types of models than neural networks
  art/attacks/carlini.py
  art/attacks/deepfool.py
  art/attacks/elastic_net.py
  art/attacks/fast_gradient.py
  art/attacks/newtonfool.py
  art/attacks/saliency_map.py
  art/attacks/spatial_transformation.py
  art/attacks/universal_perturbation.py
  art/attacks/virtual_adversarial.py
  art/attacks/zoo.py
  art/classifiers/classifier.py
  art/classifiers/detector_classifier.py
  art/classifiers/ensemble.py
  art/classifiers/keras.py
  art/classifiers/mxnet.py
  art/classifiers/pytorch.py
  art/classifiers/tensorflow.py
  art/detection/detector.py
  art/detection/subsetscanning/detector.py
  art/metrics.py
  art/poison_detection/activation_defence.py
  art/utils_test.py
  art/wrappers/expectation.py
  art/wrappers/query_efficient_bb.py
  examples/cifar_adversarial_training.py
  examples/data_augmentation.py
  examples/mnist_cnn_fgsm.py
  examples/mnist_poison_detection.py
  examples/mnist_transferability.py
  notebooks/adversarial-fashion-mnist-ffdl.ipynb
  notebooks/adversarial_patch.ipynb
  notebooks/attack_defense_imagenet.ipynb
  notebooks/mnist_poisoning_demo.ipynb
  tests/attacks/test_adversarial_patch.py
  tests/attacks/test_fast_gradient.py
  tests/attacks/test_newtonfool.py
  tests/attacks/test_virtual_adversarial.py
  tests/classifiers/test_classifier.py
  tests/classifiers/test_detector_classifier.py
  tests/classifiers/test_ensemble.py
  tests/classifiers/test_keras.py
  tests/classifiers/test_mxnet.py
  tests/classifiers/test_tensorflow.py
  tests/defences/test_adversarial_trainer.py
  tests/test_metrics.py
  tests/wrappers/test_query_efficient_bb.py
Labels: enhancement

#121 adding randomized smoothing
  art/utils.py
  art/wrappers/__init__.py
  art/wrappers/randomized_smoothing.py
  docs/modules/wrappers.rst
  notebooks/randomized_smoothing_mnist.ipynb
  run_tests.sh
  test_requirements.txt
  tests/wrappers/test_randomized_smoothing.py
Labels: enhancement
