Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2020-08, with the labels that each got.

#513 Fix targeted attacks with AutoProjectedGradientDescent
  art/attacks/evasion/auto_projected_gradient_descent.py
Labels: improvement

#494 Add support for targeted attack in autoattack
  art/attacks/evasion/auto_attack.py
  art/attacks/evasion/auto_projected_gradient_descent.py
  art/attacks/evasion/square_attack.py
  tests/attacks/evasion/test_auto_attack.py
Labels: improvement

#521 Fix bug of clip value arrays in PGD pytorch
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
  tests/attacks/test_projected_gradient_descent.py
Labels: improvement

#525 Update import path for PGD in UniversalPerturbation
  art/attacks/evasion/universal_perturbation.py
Labels: improvement

#526 Update UniversalPerturbation to use true labels if provided
  art/attacks/evasion/universal_perturbation.py
Labels: improvement

#527 Wassertein attack - support unsquared images
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
  art/attacks/evasion/wasserstein.py
  tests/attacks/test_wasserstein.py
Labels: improvement

#528 Update requirements.txt to Pillow 7.1.0 to prevent vulnerabilities
  requirements.txt
Labels: security

#529 Update to ART 1.3.2
  .github/dependabot.yml
  art/__init__.py
  art/attacks/evasion/auto_attack.py
  art/attacks/evasion/auto_projected_gradient_descent.py
  art/attacks/evasion/carlini.py
  art/attacks/evasion/deepfool.py
  art/attacks/evasion/dpatch.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
  art/attacks/evasion/square_attack.py
  art/attacks/evasion/universal_perturbation.py
  art/attacks/evasion/wasserstein.py
  art/config.py
  art/defences/preprocessor/mp3_compression.py
  art/defences/trainer/adversarial_trainer_FBF_Pytorch.py
  art/estimators/object_detection/PyTorchFasterRCNN.py
  docs/conf.py
  examples/adversarial_training_FBF.py
  requirements.txt
  tests/attacks/test_projected_gradient_descent.py
  tests/attacks/test_wasserstein.py
Labels: release

#537 SquareAttack: Use model predictions if true labels not provided
  art/attacks/evasion/square_attack.py
Labels: improvement

#545 flatten weights
  art/metrics/metrics.py
  tests/metrics/test_metrics.py
Labels: improvement

#539 faster clever_t computation
  art/metrics/metrics.py
Labels: improvement

#555 Issue#554 - added requirements.txt file comment in dockerfile
  Dockerfile
Labels: improvement

#560 Update set_params for PGD
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent.py
Labels: bug

#556 Update test of ShadowAttack
  art/attacks/evasion/shadow_attack.py
  run_tests.sh
  tests/attacks/evasion/test_shadow_attack.py
  tests/attacks/evasion/test_square_attack.py
Labels: improvement

#523 Issue 346 kerastf and Mxnet integration to commonDeepLearning framework tests
  .dockerIgnore
  Makefile
  art/attacks/attack.py
  art/estimators/tensorflow.py
  conftest.py
  run_tests.sh
  tests/attacks/evasion/test_auto_projected_gradient_descent.py
  tests/attacks/evasion/test_boundary.py
  tests/attacks/evasion/test_fast_gradient.py
  tests/attacks/evasion/test_feature_adversaries.py
  tests/attacks/evasion/test_frame_saliency.py
  tests/attacks/evasion/test_shadow_attack.py
  tests/attacks/evasion/test_square_attack.py
  tests/attacks/inference/test_model_inversion.py
  tests/defences/preprocessor/test_inverse_gan.py
  tests/defences/test_adversarial_trainer_FBF.py
  tests/estimators/classification/test_common_deeplearning.json
  tests/estimators/classification/test_common_deeplearning.py
  tests/estimators/classification/test_deeplearning_common.json
  tests/estimators/classification/test_deeplearning_common.py
  tests/estimators/classification/test_deeplearning_specific.py
  tests/estimators/classification/test_keras.py
  tests/estimators/classification/test_keras_tf.py
  tests/estimators/classification/test_mxnet.py
  tests/estimators/classification/test_tensorflow.py
  tests/estimators/object_detection/test_tensorflow_faster_rcnn.py
  tests/utils.py
Labels: tests

#510 Chaining preprocessor defenses
  art/defences/preprocessor/preprocessor.py
  art/defences/preprocessor/spatial_smoothing_pytorch.py
  art/estimators/classification/pytorch.py
  requirements.txt
  run_tests.sh
  setup.py
  tests/attacks/utils.py
  tests/classifiersFrameworks/test_pytorch.py
  tests/defences/preprocessor/test_spatial_smoothing_pytorch.py
Labels: enhancement
