Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2020-07, with the labels that each got.

#491 Fixed denormalizing in InverseGAN
  utils/resources/create_inverse_gan_models.py
Labels: improvement

#495 Allow eps_step larger than eps for norms other than inf
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent.py
Labels: improvement

#493 Fix bugs in PyTorchFasterRCNN and DPatch
  art/attacks/evasion/dpatch.py
  art/config.py
  art/estimators/object_detection/PyTorchFasterRCNN.py
Labels: improvement

#499 Fix dtype in AutoProjectedGradientDescent and SquareAttack
  art/attacks/evasion/auto_projected_gradient_descent.py
  art/attacks/evasion/square_attack.py
Labels: improvement

#487 Implement the Tensorflow Faster RCNN object detector and the ShapeShifter attack.
  art/attacks/evasion/__init__.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent.py
  art/attacks/evasion/shapeshifter.py
  art/estimators/object_detection/__init__.py
  art/estimators/object_detection/pytorch_faster_rcnn.py
  art/estimators/object_detection/tensorflow_faster_rcnn.py
  art/estimators/tensorflow.py
  run_tests.sh
  tests/attacks/test_shapeshifter.py
  tests/estimators/object_detection/__init__.py
  tests/estimators/object_detection/test_tensorflow_faster_rcnn.py
Labels: enhancement

#455 Dev 1.4.0 346 unit test pytorch classifier
  Dockerfile
  art/defences/preprocessor/mp3_compression.py
  conftest.py
  run_tests.sh
  setup.cfg
  tests/attacks/evasion/test_fast_gradient.py
  tests/attacks/evasion/test_feature_adversaries.py
  tests/attacks/evasion/test_frame_saliency.py
  tests/attacks/evasion/test_shadow_attack.py
  tests/attacks/inference/test_model_inversion.py
  tests/attacks/test_adversarial_patch.py
  tests/classifiersFrameworks/__init__.py
  tests/classifiersFrameworks/test_tensorflow.py
  tests/classifiersFrameworks/utils.py
  tests/defences/preprocessor/test_mp3_compression.py
  tests/defences/preprocessor/test_resample.py
  tests/defences/preprocessor/test_video_compression.py
  tests/defences/test_adversarial_trainer.py
  tests/estimators/classification/test_common_deeplearning.json
  tests/estimators/classification/test_common_deeplearning.py
  tests/estimators/classification/test_keras.py
  tests/estimators/classification/test_pytorch.py
  tests/estimators/classification/test_tensorflow.py
  tests/utils.py
Labels: tests

#500 Add targeted as property of EvasionAttack
  art/attacks/attack.py
  art/attacks/evasion/auto_attack.py
  art/attacks/evasion/auto_projected_gradient_descent.py
  art/attacks/evasion/boundary.py
  art/attacks/evasion/carlini.py
  art/attacks/evasion/elastic_net.py
  art/attacks/evasion/fast_gradient.py
  art/attacks/evasion/feature_adversaries.py
  art/attacks/evasion/frame_saliency.py
  art/attacks/evasion/hop_skip_jump.py
  art/attacks/evasion/pixel_threshold.py
  art/attacks/evasion/shadow_attack.py
  art/attacks/evasion/simba.py
  art/attacks/evasion/targeted_universal_perturbation.py
  art/attacks/evasion/virtual_adversarial.py
  art/attacks/evasion/wasserstein.py
  art/attacks/evasion/zoo.py
Labels: enhancement

#506 Debug fbf pytorch
  art/defences/trainer/adversarial_trainer_FBF_Pytorch.py
  examples/adversarial_training_FBF.py
Labels: improvement

#508 Fix numerical precision in AutoAttack success criteria
  art/attacks/evasion/auto_attack.py
Labels: improvement

#511 Add `verbose` parameter
  art/attacks/evasion/carlini.py
  art/attacks/evasion/deepfool.py
Labels: improvement
