Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2020-03, with the labels that each got.

#318 Adversarial audio examples
  data/images/adversarial_audio_waveform.png
  notebooks/README.md
  notebooks/adversarial_audio_examples.ipynb
Labels: enhancement

#326 Enable pytorch classifiers to flexibly select device
  art/classifiers/pytorch.py
  tests/classifiers/test_pytorch.py
Labels: improvement

#324 Implementation of Backdoor Poisoning Attacks
  art/attacks/__init__.py
  art/attacks/attack.py
  art/attacks/poisoning/__init__.py
  art/attacks/poisoning/backdoor_attack.py
  art/attacks/poisoning/perturbations/__init__.py
  art/attacks/poisoning/perturbations/image_perturbations.py
  data/backdoors/alert.png
  docs/guide/notebooks.rst
  docs/modules/attacks/poisoning.rst
  examples/mnist_poison_detection.py
  notebooks/poisoning_dataset_mnist.ipynb
  requirements.txt
  run_tests.sh
  test_requirements.txt
  tests/attacks/test_backdoor_attack.py
Labels: attack

#327 Example notebook for adversarial attacks on video action recognition
  data/images/adversarial_basketball.gif
  data/images/basketball.gif
  notebooks/README.md
  notebooks/adversarial_action_recognition.ipynb
Labels: enhancement

#320 Implement defence evaluation 12 - EMPIR
  .gitignore
  art/classifiers/tensorflow.py
  notebooks/adaptive_defence_evaluations/evaluation_12_EMPIR.ipynb
Labels: enhancement

#325 Update method fit_generator in all classifiers
  art/classifiers/classifier.py
  art/classifiers/keras.py
  art/classifiers/mxnet.py
  art/classifiers/pytorch.py
  art/classifiers/tensorflow.py
  art/data_generators.py
  docs/modules/data_generators.rst
  examples/get_started_mxnet.py
  examples/get_started_pytorch.py
  examples/get_started_tensorflow.py
  examples/get_started_tensorflow_v2.py
  tests/classifiers/test_keras_tf.py
  tests/classifiersFrameworks/test_keras.py
  tests/classifiersFrameworks/test_tensorflow.py
  tests/defences/test_adversarial_trainer.py
  tests/test_data_generators.py
Labels: improvement

#349 fix bug in poisoning notebook
  notebooks/poisoning_dataset_mnist.ipynb
Labels: bug
