Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2020-06, with the labels that each got.

#422 Implement Wassertein attack
  README-cn.md
  README.md
  art/attacks/evasion/__init__.py
  art/attacks/evasion/wasserstein.py
  run_tests.sh
  tests/attacks/test_wasserstein.py
Labels: enhancement

#409 Implement Shadow Attack
  README-cn.md
  README.md
  art/attacks/evasion/__init__.py
  art/attacks/evasion/feature_adversaries.py
  art/attacks/evasion/shadow_attack.py
  art/defences/preprocessor/gaussian_augmentation.py
  art/estimators/certification/__init__.py
  art/estimators/certification/randomized_smoothing/__init__.py
  art/estimators/certification/randomized_smoothing/pytorch.py
  art/estimators/certification/randomized_smoothing/randomized_smoothing.py
  art/estimators/certification/randomized_smoothing/tensorflow.py
  art/estimators/classification/pytorch.py
  art/estimators/classification/tensorflow.py
  art/estimators/pytorch.py
  art/wrappers/__init__.py
  docs/index.rst
  docs/modules/estimators/certification.rst
  docs/modules/estimators/certification_randomized_smoothing.rst
  docs/modules/wrappers.rst
  examples/get_started_tensorflow_v2.py
  notebooks/output_randomized_smoothing_mnist.ipynb
  run_tests.sh
  tests/attacks/evasion/test_shadow_attack.py
  tests/estimators/certification/__init__.py
  tests/estimators/certification/test_randomized_smoothing.py
  tests/estimators/classification/test_detector_classifier.py
  tests/estimators/classification/test_pytorch.py
  tests/utils.py
Labels: enhancement

#428 Attribute inference attacks
  art/attacks/__init__.py
  art/attacks/attack.py
  art/attacks/inference/__init__.py
  art/attacks/inference/attribute_inference.py
  art/estimators/classification/scikitlearn.py
  art/utils.py
  tests/attacks/inference/test_attribute_inference.py
Labels: enhancement

#437 Remove tanh_smoother from art.uitls.tanh_to_original
  art/attacks/evasion/carlini.py
  art/utils.py
Labels: improvement

#438 Add H.264/MPEG-4 AVC video compression defense
  Dockerfile
  README-cn.md
  README.md
  art/config.py
  art/defences/preprocessor/__init__.py
  art/defences/preprocessor/video_compression.py
  setup.py
  test_requirements.txt
  tests/defences/preprocessor/test_video_compression.py
Labels: enhancement

#440 Improve default values for apply_{fit,predict} arguments in defense preprocessors
  art/defences/preprocessor/gaussian_augmentation.py
  art/defences/preprocessor/jpeg_compression.py
  art/defences/preprocessor/mp3_compression.py
  art/defences/preprocessor/resample.py
  tests/defences/test_gaussian_augmentation.py
Labels: improvement

#400 Implement AutoAttack
  README-cn.md
  README.md
  art/attacks/evasion/__init__.py
  art/attacks/evasion/auto_attack.py
  art/attacks/evasion/auto_projected_gradient_descent.py
  art/attacks/evasion/square_attack.py
  tests/attacks/evasion/test_auto_attack.py
  tests/attacks/evasion/test_auto_projected_gradient_descent.py
  tests/attacks/evasion/test_square_attack.py
Labels: enhancement

#439 Add new module and implementations for Inference Attacks
  README-cn.md
  README.md
  art/attacks/__init__.py
  art/attacks/attack.py
  art/attacks/inference/__init__.py
  art/attacks/inference/attribute_inference.py
  art/attacks/inference/model_inversion.py
  art/classifiers/scikitlearn/__init__.py
  art/estimators/classification/scikitlearn.py
  art/utils.py
  data/images/adversarial_basketball.gif
  notebooks/model_inversion_attacks_mnist.ipynb
  run_tests.sh
  tests/attacks/inference/__init__.py
  tests/attacks/inference/test_attribute_inference.py
  tests/attacks/inference/test_model_inversion.py
  tests/attacks/utils.py
Labels: enhancement

#444 Update READMEs for ART 1.3.0
  CONTRIBUTING-cn.md
  README-cn.md
  README.md
  docs/images/adversarial_threats_art.png
  docs/images/adversarial_threats_attacker.png
  docs/images/art_logo_3d_1.png
  setup.py
  test_requirements.txt
Labels: documentation

#435 Adds Fast is better than free protocol for adversarial training
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent.py
  art/defences/trainer/__init__.py
  art/defences/trainer/adversarial_trainer_FBF.py
  art/defences/trainer/adversarial_trainer_FBF_Pytorch.py
  conftest.py
  examples/adversarial_training_FBF.py
  tests/defences/test_adversarial_trainer_FBF.py
Labels: enhancement

#442 Allow DataGenerator for ActivationDefence
  art/defences/detector/poison/activation_defence.py
  tests/defences/detector/poison/test_activation_defence.py
Labels: improvement

#449 Update travis.yml and add dependabot.yml
  .travis.yml
  dependabot.yml
  setup.py
  test_requirements.txt
Labels: improvement

#458 Keras wildcards
  art/estimators/classification/keras.py
  tests/estimators/classification/test_keras_tf.py
  tests/utils.py
Labels: enhancement

#447 Add progress bar to ART
  art/attacks/evasion/adversarial_patch/adversarial_patch_numpy.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_tensorflow.py
  art/attacks/evasion/boundary.py
  art/attacks/evasion/carlini.py
  art/attacks/evasion/decision_tree_attack.py
  art/attacks/evasion/deepfool.py
  art/attacks/evasion/dpatch.py
  art/attacks/evasion/elastic_net.py
  art/attacks/evasion/frame_saliency.py
  art/attacks/evasion/hclu.py
  art/attacks/evasion/hop_skip_jump.py
  art/attacks/evasion/newtonfool.py
  art/attacks/evasion/pixel_threshold.py
  art/attacks/evasion/saliency_map.py
  art/attacks/evasion/shadow_attack.py
  art/attacks/evasion/spatial_transformation.py
  art/attacks/evasion/universal_perturbation.py
  art/attacks/evasion/virtual_adversarial.py
  art/attacks/evasion/wasserstein.py
  art/attacks/evasion/zoo.py
  art/attacks/extraction/functionally_equivalent_extraction.py
  art/attacks/extraction/knockoff_nets.py
  art/attacks/inference/model_inversion.py
  art/attacks/poisoning/poisoning_attack_svm.py
  art/defences/detector/evasion/subsetscanning/detector.py
  art/defences/preprocessor/jpeg_compression.py
  art/defences/preprocessor/mp3_compression.py
  art/defences/preprocessor/pixel_defend.py
  art/defences/preprocessor/variance_minimization.py
  art/defences/preprocessor/video_compression.py
  art/defences/trainer/adversarial_trainer.py
  art/defences/trainer/adversarial_trainer_madry_pgd.py
  art/estimators/certification/randomized_smoothing/randomized_smoothing.py
  art/estimators/classification/keras.py
  art/estimators/estimator.py
  art/metrics/gradient_check.py
  art/metrics/metrics.py
  art/metrics/verification_decisions_trees.py
  tests/defences/test_adversarial_trainer.py
  tests/defences/test_adversarial_trainer_madry_pgd.py
Labels: improvement

#463 Fix and rerun audio and video notebooks
  notebooks/adversarial_action_recognition.ipynb
  notebooks/adversarial_audio_examples.ipynb
Labels: improvement

#467 fix thermometer encoding
  art/defences/preprocessor/thermometer_encoding.py
  art/estimators/classification/keras.py
  tests/defences/test_thermometer_encoding.py
Labels: bug

#468 Add fixes and improvements related to thermometer encoding
  art/defences/preprocessor/thermometer_encoding.py
  art/estimators/classification/keras.py
  tests/defences/test_thermometer_encoding.py
Labels: enhancement

#476 Fix DeepFool
  art/attacks/evasion/deepfool.py
Labels: improvement

#479 Enable index labels in method classifier.fit
  art/estimators/classification/keras.py
  art/estimators/classification/mxnet.py
  art/estimators/classification/pytorch.py
  art/estimators/classification/tensorflow.py
Labels: improvement

#480 Make internal import paths explicit for AdversarialPatch and PGD
  art/attacks/evasion/__init__.py
Labels: improvement

#481 Add set_params in multi-framework attacks
  art/attacks/evasion/adversarial_patch/adversarial_patch.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent.py
  notebooks/attack_defence_imagenet.ipynb
Labels: improvement

#482 Improve input type handling in MP3 compression
  art/defences/preprocessor/mp3_compression.py
  notebooks/adversarial_audio_examples.ipynb
Labels: enhancement
