Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2020-12, with the labels that each got.

#778 fix max_iters issue in SVM notebook
  notebooks/poisoning_attack_svm.ipynb
Labels: improvement

#762 Edit clever_t to mitigate OOM and long runtime issues
  art/metrics/metrics.py
Labels: improvement

#787 Correct unclear words in cn README
  README-cn.md
Labels: documentation

#773 Add Lingvo test runner to CI
  .github/workflows/ci.yml
  conftest.py
  setup.cfg
  tests/attacks/evasion/test_imperceptible_asr_pytorch.py
  tests/estimators/classification/test_deeplearning_specific.py
  tests/estimators/speech_recognition/test_pytorch_deep_speech.py
  tests/estimators/speech_recognition/test_tensorflow_lingvo.py
  tests/preprocessing/audio/test_l_filter_pytorch.py
Labels: tests

#784 Add Carlini and Wagner audio attack on ASR systems
  art/attacks/evasion/adversarial_asr.py
  art/attacks/evasion/imperceptible_asr/imperceptible_asr.py
  tests/attacks/evasion/conftest.py
  tests/attacks/evasion/test_adversarial_asr.py
  tests/attacks/evasion/test_imperceptible_asr.py
Labels: improvement

#789 Add model in __init__() of PyTorchFasterRCNN
  art/estimators/object_detection/pytorch_faster_rcnn.py
Labels: bug

#790 Updates for Label Only membership inference attack
  art/attacks/inference/membership_inference/label_only_boundary_distance.py
  tests/attacks/inference/membership_inference/test_label_only_boundary_distance.py
Labels: improvement

#799 Use auto tqdm imports for notebook support
  art/attacks/evasion/adversarial_patch/adversarial_patch_numpy.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_tensorflow.py
  art/attacks/evasion/boundary.py
  art/attacks/evasion/carlini.py
  art/attacks/evasion/decision_tree_attack.py
  art/attacks/evasion/deepfool.py
  art/attacks/evasion/dpatch.py
  art/attacks/evasion/dpatch_robust.py
  art/attacks/evasion/elastic_net.py
  art/attacks/evasion/frame_saliency.py
  art/attacks/evasion/hclu.py
  art/attacks/evasion/hop_skip_jump.py
  art/attacks/evasion/newtonfool.py
  art/attacks/evasion/pixel_threshold.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_numpy.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_tensorflow_v2.py
  art/attacks/evasion/saliency_map.py
  art/attacks/evasion/shadow_attack.py
  art/attacks/evasion/spatial_transformation.py
  art/attacks/evasion/universal_perturbation.py
  art/attacks/evasion/virtual_adversarial.py
  art/attacks/evasion/wasserstein.py
  art/attacks/evasion/zoo.py
  art/attacks/extraction/knockoff_nets.py
  art/attacks/inference/model_inversion/mi_face.py
  art/attacks/poisoning/feature_collision_attack.py
  art/attacks/poisoning/poisoning_attack_svm.py
  art/defences/detector/evasion/subsetscanning/detector.py
  art/defences/preprocessor/jpeg_compression.py
  art/defences/preprocessor/mp3_compression.py
  art/defences/preprocessor/pixel_defend.py
  art/defences/preprocessor/variance_minimization.py
  art/defences/preprocessor/video_compression.py
  art/defences/trainer/adversarial_trainer.py
  art/defences/trainer/adversarial_trainer_fbf_pytorch.py
  art/estimators/certification/randomized_smoothing/randomized_smoothing.py
  art/estimators/estimator.py
  art/estimators/poison_mitigation/neural_cleanse/keras.py
  art/estimators/poison_mitigation/strip/strip.py
  art/metrics/gradient_check.py
  art/metrics/metrics.py
  art/metrics/verification_decisions_trees.py
  art/preprocessing/audio/l_filter/l_filter.py
  art/preprocessing/audio/l_filter/l_filter_pytorch.py
  art/utils.py
Labels: improvement

#780 Increase precision for exponentiation in Wasserstein
  art/attacks/evasion/wasserstein.py
Labels: improvement

#802 Update checks for scaling inputs in PixelThreshold
  art/attacks/evasion/pixel_threshold.py
  tests/attacks/test_pixel_attack.py
  tests/attacks/test_threshold_attack.py
Labels: improvement

#805 Create copies of inputs to protect against overwriting inputs
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_tensorflow_v2.py
Labels: improvement
