Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2020-01, with the labels that each got.

#232 implement copycat cnn attack
  art/attacks/extraction/copycat_cnn.py
  tests/attacks/test_copycat_cnn.py
Labels: attack, enhancement

#254 Update documentation for ART v1.1.0
  art/attacks/__init__.py
  art/attacks/evasion/__init__.py
  art/attacks/extraction/__init__.py
  art/attacks/poisoning/__init__.py
  art/classifiers/keras.py
  docs/index.rst
  docs/modules/attacks.rst
  docs/modules/attacks/evasion.rst
  docs/modules/attacks/extraction.rst
  docs/modules/attacks/poisoning.rst
Labels: documentation

#262 Add analysis of unit test code coverage
  .coveragerc
  README-cn.md
  README.md
  run_tests.sh
  test_requirements.txt
Labels: improvement

#261 Knockoff nets
  art/attacks/extraction/knockoff_nets.py
  run_tests.sh
  tests/attacks/test_knockoff_nets.py
  tests/utils_test.py
Labels: enhancement

#265 Extend unit testing
  .coveragerc
  .travis.yml
  art/attacks/extraction/__init__.py
  art/classifiers/tensorflow.py
  art/data_generators.py
  art/poison_detection/activation_defence.py
  art/visualization.py
  codecov.yml
  examples/mnist_transferability.py
  notebooks/README.md
  requirements.txt
  run_tests.sh
  setup.py
  test_requirements.txt
  tests/attacks/test_adversarial_patch.py
  tests/attacks/test_boundary.py
  tests/attacks/test_carlini.py
  tests/attacks/test_copycat_cnn.py
  tests/attacks/test_decision_tree_attack.py
  tests/attacks/test_deepfool.py
  tests/attacks/test_elastic_net.py
  tests/attacks/test_fast_gradient.py
  tests/attacks/test_functionally_equivalent_extraction.py
  tests/attacks/test_hclu.py
  tests/attacks/test_hop_skip_jump.py
  tests/attacks/test_iterative_method.py
  tests/attacks/test_knockoff_nets.py
  tests/attacks/test_newtonfool.py
  tests/attacks/test_poisoning_attack_svm.py
  tests/attacks/test_projected_gradient_descent.py
  tests/attacks/test_saliency_map.py
  tests/attacks/test_spatial_transformation.py
  tests/attacks/test_universal_perturbation.py
  tests/attacks/test_virtual_adversarial.py
  tests/attacks/test_zoo.py
  tests/classifiers/test_GPy.py
  tests/classifiers/test_blackbox.py
  tests/classifiers/test_catboost.py
  tests/classifiers/test_classifier.py
  tests/classifiers/test_detector_classifier.py
  tests/classifiers/test_ensemble.py
  tests/classifiers/test_keras.py
  tests/classifiers/test_keras_tf.py
  tests/classifiers/test_lightgbm.py
  tests/classifiers/test_mxnet.py
  tests/classifiers/test_pytorch.py
  tests/classifiers/test_scikitlearn.py
  tests/classifiers/test_tensorflow.py
  tests/classifiers/test_tensorflow_v2.py
  tests/classifiers/test_xgboost.py
  tests/defences/test_adversarial_trainer.py
  tests/metrics/test_metrics.py
  tests/metrics/test_verification_decision_trees.py
  tests/poison_detection/test_provenance_defence.py
  tests/poison_detection/test_roni.py
  tests/test_utils.py
  tests/utils_test.py
Labels: improvement

#260 Added random_eps parameter
  art/attacks/evasion/projected_gradient_descent.py
Labels: enhancement

#266 Pandas Dataframe and other non-ndarray input Support
  art/attacks/attack.py
  art/classifiers/classifier.py
  run_tests.sh
  tests/attacks/test_input_filter.py
  tests/classifiers/test_input_filter.py
Labels: enhancement
