Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2020-09, with the labels that each got.

#575 Support string type for infinity norm in attacks
  art/attacks/evasion/auto_attack.py
  art/attacks/evasion/auto_projected_gradient_descent.py
  art/attacks/evasion/fast_gradient.py
  art/attacks/evasion/hop_skip_jump.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_numpy.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
  art/attacks/evasion/square_attack.py
  art/attacks/evasion/targeted_universal_perturbation.py
  art/attacks/evasion/universal_perturbation.py
  art/utils.py
Labels: improvement

#574 Extend framework-specific preprocessing defences to TensorFlow v2
  art/defences/preprocessor/__init__.py
  art/defences/preprocessor/preprocessor.py
  art/defences/preprocessor/spatial_smoothing_pytorch.py
  art/defences/preprocessor/spatial_smoothing_tensorflow.py
  art/estimators/classification/pytorch.py
  art/estimators/pytorch.py
  art/estimators/tensorflow.py
  run_tests.sh
  tests/classifiersFrameworks/test_pytorch.py
  tests/classifiersFrameworks/test_tensorflow.py
Labels: enhancement

#573 Add new membership inference attacks
  Dockerfile
  art/attacks/inference/__init__.py
  art/attacks/inference/membership_inference.py
  art/defences/detector/evasion/detector.py
  art/defences/detector/evasion/subsetscanning/detector.py
  art/estimators/certification/randomized_smoothing/pytorch.py
  art/estimators/certification/randomized_smoothing/tensorflow.py
  art/estimators/classification/detector_classifier.py
  art/estimators/classification/ensemble.py
  art/estimators/classification/keras.py
  art/estimators/classification/mxnet.py
  art/estimators/classification/pytorch.py
  art/estimators/classification/tensorflow.py
  art/estimators/encoding/tensorflow.py
  art/estimators/estimator.py
  art/estimators/generation/tensorflow.py
  art/estimators/keras.py
  art/estimators/mxnet.py
  art/estimators/object_detection/pytorch_faster_rcnn.py
  art/estimators/pytorch.py
  art/estimators/tensorflow.py
  art/utils.py
  conftest.py
  notebooks/attack_attribute_inference.ipynb
  notebooks/attack_membership_inference.ipynb
  requirements.txt
  setup.py
  tests/attacks/inference/test_membership_inference.py
  tests/attacks/test_wasserstein.py
  tests/defences/preprocessor/test_spatial_smoothing_pytorch.py
  tests/estimators/classification/test_classifier.py
  tests/estimators/classification/test_deeplearning_common.py
  tests/utils.py
Labels: enhancement

#561 Implement Adversarial Embedding Poisoning Attack
  art/attacks/attack.py
  art/attacks/poisoning/__init__.py
  art/attacks/poisoning/adversarial_embedding_attack.py
  art/attacks/poisoning/backdoor_attack.py
  art/attacks/poisoning/perturbations/image_perturbations.py
  docs/modules/attacks.rst
  notebooks/poisoning_attack_embedding.ipynb
  run_tests.sh
  tests/attacks/test_adversarial_embedding.py
  utils/data/images/adv_embedding_arch.png
Labels: enhancement

#591 fix issue #585
  art/defences/preprocessor/thermometer_encoding.py
  tests/defences/test_thermometer_encoding.py
Labels: bug

#598 Update documentation
  art/attacks/__init__.py
  art/attacks/evasion/pixel_threshold.py
  art/attacks/poisoning/adversarial_embedding_attack.py
  art/defences/preprocessor/spatial_smoothing_pytorch.py
  art/defences/preprocessor/spatial_smoothing_tensorflow.py
  docs/index.rst
  docs/modules/attacks/evasion.rst
  docs/modules/attacks/inference/attribute_inference.rst
  docs/modules/attacks/inference/membership_inference.rst
  docs/modules/attacks/inference/model_inversion.rst
  docs/modules/attacks/poisoning.rst
  docs/modules/defences/preprocessor.rst
  docs/modules/estimators/object_detection.rst
  docs/modules/metrics.rst
  docs/modules/tests/utils.rst
Labels: documentation

#603 Update progress bars in PGDs and FBF adversarial trainer
  art/attacks/evasion/carlini.py
  art/attacks/evasion/deepfool.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_numpy.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_tensorflow_v2.py
  art/defences/trainer/adversarial_trainer.py
  art/defences/trainer/adversarial_trainer_fbf_pytorch.py
Labels: improvement

#605 ASR attack pytorch
  art/attacks/evasion/__init__.py
  art/attacks/evasion/imperceptible_asr/__init__.py
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
  art/estimators/speech_recognition/__init__.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
  art/estimators/speech_recognition/speech_recognizer.py
  docs/index.rst
  docs/modules/estimators/speech_recognition.rst
  run_tests.sh
  tests/attacks/evasion/test_imperceptible_asr_pytorch.py
  tests/estimators/speech_recognition/__init__.py
  tests/estimators/speech_recognition/test_pytorch_deep_speech.py
Labels: enhancement

#604 Implement Neural Cleanse Defense
  art/defences/transformer/__init__.py
  art/defences/transformer/evasion/__init__.py
  art/defences/transformer/evasion/defensive_distillation.py
  art/defences/transformer/poison/__init__.py
  art/defences/transformer/poison/neural_cleanse.py
  art/estimators/certification/abstain.py
  art/estimators/certification/neural_cleanse/__init__.py
  art/estimators/certification/neural_cleanse/keras.py
  art/estimators/certification/neural_cleanse/neural_cleanse.py
  docs/index.rst
  docs/modules/estimators/certification_neural_cleanse.rst
  notebooks/poisoning_defense_neural_cleanse.ipynb
  run_tests.sh
  tests/defences/test_neural_cleanse.py
  utils/data/images/zero_to_one.png
Labels: enhancement

#599 Add targeted version of DPatch
  art/attacks/evasion/dpatch.py
  art/estimators/object_detection/pytorch_faster_rcnn.py
  tests/attacks/evasion/test_dpatch.py
Labels: improvement

#611 Update progress bar descriptions in PGD
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_tensorflow_v2.py
Labels: improvement

#613 Update imports and default values to stay framework-independent
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
  art/defences/preprocessor/spatial_smoothing_pytorch.py
Labels: improvement

#612 Update internal imports
  art/attacks/__init__.py
  art/attacks/evasion/auto_projected_gradient_descent.py
  art/attacks/inference/__init__.py
  art/defences/__init__.py
  art/defences/detector/__init__.py
  art/defences/detector/evasion/__init__.py
  art/defences/detector/evasion/detector.py
  art/defences/detector/evasion/subsetscanning/__init__.py
  art/defences/detector/poison/__init__.py
  art/defences/detector/poisoning/__init__.py
  art/defences/detector/poisoning/activation_defence.py
  art/defences/detector/poisoning/clustering_analyzer.py
  art/defences/detector/poisoning/ground_truth_evaluator.py
  art/defences/detector/poisoning/poison_filtering_defence.py
  art/defences/detector/poisoning/provenance_defense.py
  art/defences/detector/poisoning/roni.py
  art/defences/detector/poisoning/spectral_signature_defense.py
  art/defences/transformer/__init__.py
  art/defences/transformer/evasion/__init__.py
  art/defences/transformer/poison/__init__.py
  art/defences/transformer/poisoning/__init__.py
  art/defences/transformer/poisoning/neural_cleanse.py
  art/estimators/__init__.py
  art/estimators/certification/__init__.py
  art/estimators/estimator.py
  art/estimators/pytorch.py
  art/estimators/tensorflow.py
  art/metrics/metrics.py
  examples/mnist_poison_detection.py
  notebooks/poisoning_attack_embedding.ipynb
  notebooks/poisoning_dataset_mnist.ipynb
  notebooks/poisoning_defense_neural_cleanse.ipynb
  notebooks/provenance_defence.ipynb
  tests/defences/detector/evasion/subsetscanning/test_detector.py
  tests/defences/detector/poison/test_activation_defence.py
  tests/defences/detector/poison/test_clustering_analyzer.py
  tests/defences/detector/poison/test_ground_truth_evaluator.py
  tests/defences/detector/poison/test_provenance_defence.py
  tests/defences/detector/poison/test_roni.py
  tests/defences/detector/poison/test_spectral_signature_defense.py
  tests/defences/preprocessor/test_jpeg_compression.py
  tests/defences/test_defensive_distillation.py
  tests/defences/test_neural_cleanse.py
Labels: improvement

#621 fix bugs for asr and deepspeech
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
  tests/estimators/speech_recognition/test_pytorch_deep_speech.py
Labels: bug
