Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2020-10, with the labels that each got.

#631 Update check for Keras type in KerasClassifier
  art/estimators/classification/keras.py
Labels: enhancement

#635 Fix deepspeech estimator cornercase
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
  tests/estimators/speech_recognition/test_pytorch_deep_speech.py
Labels: improvement

#586 Dev 1.4.0 459 remove classifier none
  Dockerfile
  conftest.py
  run_tests.sh
  setup.cfg
  tests/attacks/conftest.py
  tests/attacks/evasion/test_auto_attack.py
  tests/attacks/evasion/test_auto_projected_gradient_descent.py
  tests/attacks/evasion/test_boundary.py
  tests/attacks/evasion/test_dpatch.py
  tests/attacks/evasion/test_fast_gradient.py
  tests/attacks/evasion/test_feature_adversaries.py
  tests/attacks/evasion/test_frame_saliency.py
  tests/attacks/evasion/test_imperceptible_asr_pytorch.py
  tests/attacks/evasion/test_shadow_attack.py
  tests/attacks/evasion/test_square_attack.py
  tests/attacks/inference/test_attribute_inference.py
  tests/attacks/inference/test_membership_inference.py
  tests/attacks/inference/test_model_inversion.py
  tests/classifiersFrameworks/test_pytorch.py
  tests/classifiersFrameworks/test_tensorflow.py
  tests/defences/preprocessor/test_inverse_gan.py
  tests/defences/preprocessor/test_jpeg_compression.py
  tests/defences/preprocessor/test_mp3_compression.py
  tests/defences/preprocessor/test_resample.py
  tests/defences/preprocessor/test_spatial_smoothing.py
  tests/defences/preprocessor/test_spatial_smoothing_pytorch.py
  tests/defences/preprocessor/test_spatial_smoothing_tensorflow.py
  tests/defences/preprocessor/test_video_compression.py
  tests/estimators/classification/test_deeplearning_common.py
  tests/estimators/classification/test_deeplearning_specific.py
  tests/utils.py
Labels: tests

#636 Revert module name
  art/defences/detector/__init__.py
  art/defences/detector/poison/__init__.py
  art/defences/detector/poison/activation_defence.py
  art/defences/detector/poison/clustering_analyzer.py
  art/defences/detector/poison/ground_truth_evaluator.py
  art/defences/detector/poison/poison_filtering_defence.py
  art/defences/detector/poison/provenance_defense.py
  art/defences/detector/poison/roni.py
  art/defences/detector/poison/spectral_signature_defense.py
  art/defences/detector/poisoning/__init__.py
  examples/mnist_poison_detection.py
  notebooks/poisoning_attack_embedding.ipynb
  notebooks/poisoning_dataset_mnist.ipynb
  notebooks/poisoning_defense_neural_cleanse.ipynb
  notebooks/provenance_defence.ipynb
  tests/defences/detector/poison/test_activation_defence.py
  tests/defences/detector/poison/test_clustering_analyzer.py
  tests/defences/detector/poison/test_ground_truth_evaluator.py
  tests/defences/detector/poison/test_provenance_defence.py
  tests/defences/detector/poison/test_roni.py
  tests/defences/detector/poison/test_spectral_signature_defense.py
Labels: improvement

#639 Deepspeech notebook
  notebooks/asr_deepspeech_examples.ipynb
Labels: enhancement

#637 Update to ART 1.4.1
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
  art/defences/detector/__init__.py
  art/defences/detector/poison/__init__.py
  art/defences/detector/poison/activation_defence.py
  art/defences/detector/poison/clustering_analyzer.py
  art/defences/detector/poison/ground_truth_evaluator.py
  art/defences/detector/poison/poison_filtering_defence.py
  art/defences/detector/poison/provenance_defense.py
  art/defences/detector/poison/roni.py
  art/defences/detector/poison/spectral_signature_defense.py
  art/defences/detector/poisoning/__init__.py
  art/estimators/classification/keras.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
  examples/mnist_poison_detection.py
  notebooks/asr_deepspeech_examples.ipynb
  notebooks/poisoning_attack_embedding.ipynb
  notebooks/poisoning_dataset_mnist.ipynb
  notebooks/poisoning_defense_neural_cleanse.ipynb
  notebooks/provenance_defence.ipynb
  tests/defences/detector/poison/test_activation_defence.py
  tests/defences/detector/poison/test_clustering_analyzer.py
  tests/defences/detector/poison/test_ground_truth_evaluator.py
  tests/defences/detector/poison/test_provenance_defence.py
  tests/defences/detector/poison/test_roni.py
  tests/defences/detector/poison/test_spectral_signature_defense.py
  tests/estimators/speech_recognition/test_pytorch_deep_speech.py
Labels: release

#642 Fix bugs in ASR, Deepspeech and the notebook
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
  notebooks/asr_deepspeech_examples.ipynb
  tests/attacks/evasion/test_imperceptible_asr_pytorch.py
Labels: bug

#615 Github Actions CI Pipeline
  .github/dependabot.yml
  .github/workflows/ci.yml
Labels: enhancement

#647 Add verbose argument to all attacks and defences
  art/attacks/evasion/adversarial_patch/adversarial_patch.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_numpy.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_tensorflow.py
  art/attacks/evasion/auto_projected_gradient_descent.py
  art/attacks/evasion/boundary.py
  art/attacks/evasion/decision_tree_attack.py
  art/attacks/evasion/deepfool.py
  art/attacks/evasion/dpatch.py
  art/attacks/evasion/elastic_net.py
  art/attacks/evasion/frame_saliency.py
  art/attacks/evasion/hclu.py
  art/attacks/evasion/hop_skip_jump.py
  art/attacks/evasion/newtonfool.py
  art/attacks/evasion/pixel_threshold.py
  art/attacks/evasion/saliency_map.py
  art/attacks/evasion/shadow_attack.py
  art/attacks/evasion/spatial_transformation.py
  art/attacks/evasion/square_attack.py
  art/attacks/evasion/universal_perturbation.py
  art/attacks/evasion/virtual_adversarial.py
  art/attacks/evasion/wasserstein.py
  art/attacks/evasion/zoo.py
  art/attacks/extraction/knockoff_nets.py
  art/attacks/inference/model_inversion/mi_face.py
  art/attacks/poisoning/feature_collision_attack.py
  art/attacks/poisoning/poisoning_attack_svm.py
  art/defences/detector/evasion/subsetscanning/detector.py
  art/defences/preprocessor/jpeg_compression.py
  art/defences/preprocessor/mp3_compression.py
  art/defences/preprocessor/pixel_defend.py
  art/defences/preprocessor/spatial_smoothing.py
  art/defences/preprocessor/spatial_smoothing_pytorch.py
  art/defences/preprocessor/spatial_smoothing_tensorflow.py
  art/defences/preprocessor/variance_minimization.py
  art/defences/preprocessor/video_compression.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
Labels: improvement

#648 Fix missing imports in TensorFlowFasterRCNN
  art/estimators/object_detection/tensorflow_faster_rcnn.py
Labels: bug

#646 Fix batch_size in SquareAttack
  art/attacks/evasion/square_attack.py
Labels: improvement

#651 Update loss method in KerasClassifier
  art/estimators/classification/keras.py
Labels: bug

#662 Enable lists in patch_shape of DPatch
  art/attacks/evasion/dpatch.py
Labels: improvement

#660 Unify prediction of object detectors
  art/estimators/object_detection/pytorch_faster_rcnn.py
  art/estimators/object_detection/tensorflow_faster_rcnn.py
  examples/application_object_detection.py
Labels: enhancement

#663 Enable preprocessing defences in PyTorchDeepSpeech
  art/estimators/speech_recognition/pytorch_deep_speech.py
Labels: improvement

#667 Update Dpatch to new prediction format
  art/attacks/evasion/dpatch.py
Labels: bug

#644 Dev 1.5.0 462 Separate TensorFlow 1.x and TensorFlow 2.x tests
  Dockerfile
  conftest.py
  requirements.txt
  run_tests.sh
  tests/attacks/evasion/test_auto_projected_gradient_descent.py
  tests/attacks/evasion/test_shadow_attack.py
  tests/attacks/inference/test_model_inversion.py
  tests/classifiersFrameworks/test_pytorch.py
  tests/classifiersFrameworks/test_tensorflow.py
  tests/defences/preprocessor/conftest.py
  tests/defences/preprocessor/test_jpeg_compression.py
  tests/defences/preprocessor/test_mp3_compression.py
  tests/defences/preprocessor/test_resample.py
  tests/defences/preprocessor/test_spatial_smoothing.py
  tests/defences/preprocessor/test_spatial_smoothing_pytorch.py
  tests/defences/preprocessor/test_spatial_smoothing_tensorflow.py
  tests/defences/preprocessor/test_video_compression.py
  tests/estimators/classification/test_deeplearning_common.py
  tests/estimators/classification/test_deeplearning_specific.py
  tests/utils.py
Labels: tests

#676 Set targeted to True in ImperceptibleASR
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
Labels: improvement

#677 Raise exception if target labels not provded in ImperceptibleASRPytorch.generate
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
Labels: improvement

#669 Add support PGD and FGSM attacks on PyTorchDeepSpeech estimator
  art/attacks/evasion/fast_gradient.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_numpy.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
  notebooks/asr_deepspeech_examples.ipynb
Labels: improvement

#679 Add support for tensors in loss_gradient
  art/estimators/object_detection/pytorch_faster_rcnn.py
Labels: improvement

#681 Updates for DPatch
  art/attacks/evasion/dpatch.py
Labels: improvement

#682 enable PGD masks for non-classification tasks
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_numpy.py
Labels: enhancement

#619 Add AMP support for Pytorch
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
  art/estimators/classification/pytorch.py
  conftest.py
  tests/estimators/classification/test_deeplearning_common.py
  tests/estimators/classification/test_deeplearning_specific.json
  tests/estimators/classification/test_deeplearning_specific.py
  tests/estimators/speech_recognition/test_pytorch_deep_speech.json
  tests/estimators/speech_recognition/test_pytorch_deep_speech.py
Labels: enhancement

#684 Add support for variable length input to MP3Compression
  art/defences/preprocessor/mp3_compression.py
Labels: improvement

#689 Change default return of PyTorchDeepSpeech.predict
  art/estimators/speech_recognition/pytorch_deep_speech.py
Labels: bug

#685 Update AutoProjectedGradientDescent
  art/attacks/evasion/auto_projected_gradient_descent.py
  art/estimators/classification/keras.py
  art/estimators/classification/pytorch.py
  art/estimators/classification/tensorflow.py
  tests/attacks/evasion/test_auto_attack.py
Labels: improvement

#695 Avoid using deprecated Numpy methods to create object array
  art/estimators/speech_recognition/pytorch_deep_speech.py
Labels: improvement

#696 Fix a small bug in FGM
  art/attacks/evasion/fast_gradient.py
Labels: bug
