Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2020-11, with the labels that each got.

#656 Implement STRIP Defense Against Poisoning Attacks
  art/defences/transformer/poisoning/__init__.py
  art/defences/transformer/poisoning/neural_cleanse.py
  art/defences/transformer/poisoning/strip.py
  art/estimators/__init__.py
  art/estimators/certification/__init__.py
  art/estimators/certification/neural_cleanse/__init__.py
  art/estimators/poison_mitigation/__init__.py
  art/estimators/poison_mitigation/neural_cleanse/__init__.py
  art/estimators/poison_mitigation/neural_cleanse/keras.py
  art/estimators/poison_mitigation/neural_cleanse/neural_cleanse.py
  art/estimators/poison_mitigation/strip/__init__.py
  art/estimators/poison_mitigation/strip/strip.py
  docs/modules/defences/transformer_poisoning.rst
  notebooks/README.md
  notebooks/poisoning_defence_strip.ipynb
  run_tests.sh
  tests/defences/transformer/__init__.py
  tests/defences/transformer/poisoning/__init__.py
  tests/defences/transformer/poisoning/test_strip.py
Labels: enhancement

#703 Certified accuracy #699
  notebooks/output_randomized_smoothing_mnist.ipynb
Labels: improvement

#700 Add support for multi-channel images to JpegCompression
  art/defences/preprocessor/jpeg_compression.py
  tests/defences/preprocessor/test_jpeg_compression.py
Labels: enhancement

#709 Update to ART 1.4.2
  art/attacks/evasion/adversarial_patch/adversarial_patch.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_numpy.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_tensorflow.py
  art/attacks/evasion/auto_projected_gradient_descent.py
  art/attacks/evasion/boundary.py
  art/attacks/evasion/decision_tree_attack.py
  art/attacks/evasion/deepfool.py
  art/attacks/evasion/dpatch.py
  art/attacks/evasion/elastic_net.py
  art/attacks/evasion/fast_gradient.py
  art/attacks/evasion/frame_saliency.py
  art/attacks/evasion/hclu.py
  art/attacks/evasion/hop_skip_jump.py
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
  art/attacks/evasion/newtonfool.py
  art/attacks/evasion/pixel_threshold.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_numpy.py
  art/attacks/evasion/saliency_map.py
  art/attacks/evasion/shadow_attack.py
  art/attacks/evasion/spatial_transformation.py
  art/attacks/evasion/square_attack.py
  art/attacks/evasion/universal_perturbation.py
  art/attacks/evasion/virtual_adversarial.py
  art/attacks/evasion/wasserstein.py
  art/attacks/evasion/zoo.py
  art/attacks/extraction/knockoff_nets.py
  art/attacks/inference/model_inversion/mi_face.py
  art/attacks/poisoning/feature_collision_attack.py
  art/attacks/poisoning/poisoning_attack_svm.py
  art/defences/detector/evasion/subsetscanning/detector.py
  art/defences/preprocessor/jpeg_compression.py
  art/defences/preprocessor/mp3_compression.py
  art/defences/preprocessor/pixel_defend.py
  art/defences/preprocessor/spatial_smoothing.py
  art/defences/preprocessor/spatial_smoothing_pytorch.py
  art/defences/preprocessor/spatial_smoothing_tensorflow.py
  art/defences/preprocessor/variance_minimization.py
  art/defences/preprocessor/video_compression.py
  art/estimators/classification/keras.py
  art/estimators/classification/pytorch.py
  art/estimators/classification/tensorflow.py
  art/estimators/object_detection/pytorch_faster_rcnn.py
  art/estimators/object_detection/tensorflow_faster_rcnn.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
  examples/application_object_detection.py
  notebooks/asr_deepspeech_examples.ipynb
  tests/attacks/evasion/test_auto_attack.py
  tests/attacks/evasion/test_imperceptible_asr_pytorch.py
Labels: release

#584 Add Lingvo ASR estimator
  Dockerfile
  art/estimators/speech_recognition/__init__.py
  art/estimators/speech_recognition/tensorflow_lingvo.py
  requirements.txt
  run_tests.sh
  setup.py
  tests/estimators/speech_recognition/conftest.py
  tests/estimators/speech_recognition/test_tensorflow_lingvo.py
Labels: enhancement

#701 Make ART_DATA_PATH configurable after import
  art/attacks/evasion/dpatch.py
  art/config.py
  art/defences/detector/poison/activation_defence.py
  art/defences/preprocessor/mp3_compression.py
  art/defences/preprocessor/spatial_smoothing_tensorflow.py
  art/defences/preprocessor/video_compression.py
  art/estimators/classification/GPy.py
  art/estimators/classification/catboost.py
  art/estimators/classification/keras.py
  art/estimators/classification/lightgbm.py
  art/estimators/classification/mxnet.py
  art/estimators/classification/pytorch.py
  art/estimators/classification/scikitlearn.py
  art/estimators/classification/tensorflow.py
  art/estimators/classification/xgboost.py
  art/estimators/object_detection/tensorflow_faster_rcnn.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
  art/estimators/tensorflow.py
  art/utils.py
  art/visualization.py
  notebooks/adversarial_action_recognition.ipynb
  notebooks/adversarial_audio_examples.ipynb
  notebooks/adversarial_retraining.ipynb
  notebooks/adversarial_training_mnist.ipynb
  notebooks/asr_deepspeech_examples.ipynb
  notebooks/classifier_blackbox.ipynb
  notebooks/classifier_blackbox_tesseract.ipynb
  notebooks/detection_adversarial_samples_cifar10.ipynb
  notebooks/output_randomized_smoothing_mnist.ipynb
  notebooks/poisoning_attack_feature_collision.ipynb
  tests/estimators/classification/test_deeplearning_specific.py
  tests/test_visualization.py
Labels: enhancement

#726 IBM to Trusted-AI
  docs/guide/examples.rst
Labels: documentation

#731 Fix #728: PyTorchDataGenerator always returns the same batch
  art/__init__.py
  art/data_generators.py
  docs/conf.py
  docs/guide/examples.rst
  requirements.txt
Labels: improvement

#704 Mask for AutoAttack, APGD, DPatch, and AdversarialPatch*
  art/attacks/evasion/adversarial_patch/adversarial_patch.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_numpy.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_tensorflow.py
  art/attacks/evasion/auto_attack.py
  art/attacks/evasion/auto_projected_gradient_descent.py
  art/attacks/evasion/dpatch.py
  art/attacks/evasion/fast_gradient.py
  art/attacks/evasion/hop_skip_jump.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_numpy.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_tensorflow_v2.py
  tests/attacks/test_adversarial_patch.py
Labels: enhancement

#730 Framework Specific Github Actions Runs
  .github/workflows/ci.yml
  run_tests.sh
  tests/defences/preprocessor/test_mp3_compression.py
  tests/defences/preprocessor/test_video_compression.py
Labels: tests

#741 Format fix for Membership Inference Black-box attack
  art/attacks/inference/membership_inference/black_box.py
Labels: improvement

#691 Support multi-modal inputs for PGD and FGM attacks
  art/attacks/evasion/fast_gradient.py
  art/attacks/evasion/iterative_method.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_numpy.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_tensorflow_v2.py
  art/utils.py
  tests/attacks/evasion/test_fast_gradient.py
  tests/attacks/evasion/test_frame_saliency.py
  tests/attacks/test_iterative_method.py
  tests/attacks/test_projected_gradient_descent.py
  tests/classifiersFrameworks/test_pytorch.py
  tests/classifiersFrameworks/test_tensorflow.py
  tests/metrics/test_metrics.py
Labels: enhancement

#725 Implement Clean Label Backdoor Attacks
  art/attacks/poisoning/__init__.py
  art/attacks/poisoning/clean_label_backdoor_attack.py
  art/utils.py
  docs/modules/attacks/poisoning.rst
  notebooks/poisoning_attack_clean_label_backdoor.ipynb
  run_tests.sh
  tests/attacks/poison/__init__.py
  tests/attacks/poison/test_clean_label_backdoor_attack.py
  utils/data/images/zero_to_nine.png
Labels: enhancement

#678 Update Spectral Signatures Defense
  art/defences/detector/poison/ground_truth_evaluator.py
  art/defences/detector/poison/poison_filtering_defence.py
  art/defences/detector/poison/spectral_signature_defense.py
  art/utils.py
  notebooks/poisoning_defense_activation_clustering.ipynb
  notebooks/poisoning_defense_spectral_signatures.ipynb
  run_tests.sh
  tests/defences/detector/poison/test_spectral_signature_defense.py
Labels: improvement

#736 Update default values and property definitions
  art/defences/detector/evasion/detector.py
  art/defences/detector/evasion/subsetscanning/detector.py
  art/estimators/classification/GPy.py
  art/estimators/classification/blackbox.py
  art/estimators/classification/catboost.py
  art/estimators/classification/detector_classifier.py
  art/estimators/classification/ensemble.py
  art/estimators/classification/keras.py
  art/estimators/classification/lightgbm.py
  art/estimators/classification/mxnet.py
  art/estimators/classification/pytorch.py
  art/estimators/classification/scikitlearn.py
  art/estimators/classification/tensorflow.py
  art/estimators/classification/xgboost.py
  art/estimators/encoding/tensorflow.py
  art/estimators/estimator.py
  art/estimators/generation/tensorflow.py
  art/estimators/object_detection/pytorch_faster_rcnn.py
  art/estimators/object_detection/tensorflow_faster_rcnn.py
  art/estimators/poison_mitigation/neural_cleanse/keras.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
  art/estimators/speech_recognition/tensorflow_lingvo.py
  art/wrappers/expectation.py
  art/wrappers/query_efficient_bb.py
  tests/attacks/evasion/test_shadow_attack.py
  tests/attacks/test_wasserstein.py
  tests/estimators/classification/test_classifier.py
Labels: improvement

#740 Extend and update test matrix
  .github/workflows/ci.yml
  requirements.txt
  setup.py
  tests/attacks/test_adversarial_patch.py
  tests/attacks/test_deepfool.py
  tests/attacks/test_elastic_net.py
  tests/attacks/test_hop_skip_jump.py
  tests/attacks/test_input_filter.py
  tests/attacks/test_iterative_method.py
  tests/attacks/test_knockoff_nets.py
  tests/attacks/test_newtonfool.py
  tests/attacks/test_pixel_attack.py
  tests/attacks/test_projected_gradient_descent.py
  tests/attacks/test_saliency_map.py
  tests/attacks/test_simba.py
  tests/attacks/test_spatial_transformation.py
  tests/attacks/test_targeted_universal_perturbation.py
  tests/attacks/test_threshold_attack.py
  tests/attacks/test_universal_perturbation.py
  tests/attacks/test_virtual_adversarial.py
  tests/attacks/test_zoo.py
  tests/defences/detector/poison/test_activation_defence.py
  tests/defences/test_defensive_distillation.py
  tests/metrics/test_metrics.py
  tests/utils.py
Labels: tests

#750 Fix optional parameter in infer method
  art/attacks/inference/attribute_inference/black_box.py
Labels: improvement

#654 Introduce module art.evaluations and implement Security Curve evaluation
  .gitignore
  art/evaluations/__init__.py
  art/evaluations/evaluation.py
  art/evaluations/security_curve/__init__.py
  art/evaluations/security_curve/security_curve.py
  notebooks/art_evaluations/security_curve.ipynb
Labels: enhancement

#752 Simplified Preprocessor and Postprocessor Usage and Defaults
  art/defences/postprocessor/class_labels.py
  art/defences/postprocessor/gaussian_noise.py
  art/defences/postprocessor/high_confidence.py
  art/defences/postprocessor/postprocessor.py
  art/defences/postprocessor/reverse_sigmoid.py
  art/defences/postprocessor/rounded.py
  art/defences/preprocessor/feature_squeezing.py
  art/defences/preprocessor/gaussian_augmentation.py
  art/defences/preprocessor/inverse_gan.py
  art/defences/preprocessor/jpeg_compression.py
  art/defences/preprocessor/label_smoothing.py
  art/defences/preprocessor/mp3_compression.py
  art/defences/preprocessor/pixel_defend.py
  art/defences/preprocessor/preprocessor.py
  art/defences/preprocessor/resample.py
  art/defences/preprocessor/spatial_smoothing.py
  art/defences/preprocessor/spatial_smoothing_pytorch.py
  art/defences/preprocessor/spatial_smoothing_tensorflow.py
  art/defences/preprocessor/thermometer_encoding.py
  art/defences/preprocessor/variance_minimization.py
  art/defences/preprocessor/video_compression.py
  art/preprocessing/standardisation_mean_std/standardisation_mean_std.py
  art/preprocessing/standardisation_mean_std/standardisation_mean_std_pytorch.py
  art/preprocessing/standardisation_mean_std/standardisation_mean_std_tensorflow.py
Labels: improvement

#738 Randomized Smoothing for ART Classifiers
  art/estimators/certification/randomized_smoothing/__init__.py
  art/estimators/certification/randomized_smoothing/numpy.py
Labels: enhancement

#751 Robust Dpatch
  art/attacks/evasion/__init__.py
  art/attacks/evasion/dpatch_robust.py
  examples/get_started_fasterrcnn.py
  tests/attacks/evasion/test_dpatch_robust.py
Labels: enhancement

#749 First draft of database reconstruction attack
  art/attacks/inference/reconstruction/__init__.py
  art/attacks/inference/reconstruction/white_box.py
  tests/attacks/inference/test_reconstruction.py
Labels: enhancement

#711 Change order of mask and norm steps in PGD attacks
  art/attacks/evasion/fast_gradient.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_numpy.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_tensorflow_v2.py
  tests/attacks/test_projected_gradient_descent.py
  tests/attacks/utils.py
Labels: improvement

#755 Account for fractional batches in ZOO attack
  art/attacks/evasion/zoo.py
Labels: improvement

#744 Implement impulse response filtering for sequential inputs
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_tensorflow_v2.py
  art/defences/preprocessor/preprocessor.py
  art/defences/preprocessor/spatial_smoothing_pytorch.py
  art/estimators/pytorch.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
  art/estimators/speech_recognition/tensorflow_lingvo.py
  art/estimators/tensorflow.py
  art/preprocessing/__init__.py
  art/preprocessing/l_filter/__init__.py
  art/preprocessing/l_filter/l_filter.py
  art/preprocessing/l_filter/l_filter_pytorch.py
  art/preprocessing/preprocessing.py
  art/preprocessing/standardisation_mean_std/standardisation_mean_std.py
  art/preprocessing/standardisation_mean_std/standardisation_mean_std_pytorch.py
  art/preprocessing/standardisation_mean_std/standardisation_mean_std_tensorflow.py
  conftest.py
  requirements.txt
  setup.py
  tests/metrics/test_metrics.py
  tests/preprocessing/__init__.py
  tests/preprocessing/test_l_filter.json
  tests/preprocessing/test_l_filter.py
  tests/preprocessing/test_l_filter_pytorch.json
  tests/preprocessing/test_l_filter_pytorch.py
Labels: enhancement

#761 Updates for Boundary Attack
  art/attacks/evasion/boundary.py
Labels: improvement

#759 Introduce Database Reconstruction Attack
  art/attacks/__init__.py
  art/attacks/attack.py
  art/attacks/inference/reconstruction/__init__.py
  art/attacks/inference/reconstruction/white_box.py
  art/estimators/classification/scikitlearn.py
  notebooks/attack_database_reconstruction.ipynb
  tests/attacks/inference/test_reconstruction.py
Labels: enhancement

#719 Imperceptible ASR attack independent of estimator
  .github/workflows/ci.yml
  art/attacks/evasion/__init__.py
  art/attacks/evasion/imperceptible_asr/imperceptible_asr.py
  art/utils.py
  conftest.py
  tests/attacks/evasion/conftest.py
  tests/attacks/evasion/test_imperceptible_asr.py
Labels: enhancement

#765 Development PGD
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_numpy.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_tensorflow_v2.py
Labels: improvement

#763 Support preprocessing in the pytorch imperceptable asr attack
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
  art/preprocessing/l_filter/l_filter_pytorch.py
  tests/attacks/evasion/test_imperceptible_asr_pytorch.json
  tests/attacks/evasion/test_imperceptible_asr_pytorch.py
  tests/estimators/speech_recognition/test_pytorch_deep_speech.json
  tests/estimators/speech_recognition/test_pytorch_deep_speech.py
  tests/preprocessing/test_l_filter_pytorch.py
Labels: improvement

#720 Implement Label-Only Boundary Distance Attack and Gap Attack for Membership Inference
  art/attacks/inference/membership_inference/__init__.py
  art/attacks/inference/membership_inference/black_box_rule_based.py
  art/attacks/inference/membership_inference/label_only_boundary_distance.py
  art/attacks/inference/membership_inference/label_only_gap_attack.py
  tests/attacks/inference/attribute_inference/__init__.py
  tests/attacks/inference/attribute_inference/test_black_box.py
  tests/attacks/inference/attribute_inference/test_white_box_decision_tree.py
  tests/attacks/inference/attribute_inference/test_white_box_lifestyle_decision_tree.py
  tests/attacks/inference/membership_inference/__init__.py
  tests/attacks/inference/membership_inference/test_black_box.py
  tests/attacks/inference/membership_inference/test_black_box_rule_based.py
  tests/attacks/inference/membership_inference/test_label_only_boundary_distance.py
  tests/attacks/inference/membership_inference/test_label_only_gap_attack.py
  tests/attacks/inference/model_inversion/__init__.py
  tests/attacks/inference/model_inversion/test_mi_face.py
Labels: enhancement

#760 Add general support for PyTorch in Imperceptible ASR attack
  art/attacks/evasion/imperceptible_asr/imperceptible_asr.py
  art/utils.py
  tests/attacks/evasion/conftest.py
  tests/attacks/evasion/test_imperceptible_asr.py
Labels: improvement

#768 One-hot attribute inference
  art/attacks/attack.py
  art/attacks/inference/attribute_inference/black_box.py
  art/attacks/inference/attribute_inference/white_box_decision_tree.py
  art/attacks/inference/attribute_inference/white_box_lifestyle_decision_tree.py
  tests/attacks/inference/attribute_inference/test_black_box.py
Labels: improvement
