Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2021-06, with the labels that each got.

#1001 Implement GeoDA attack
  art/attacks/evasion/__init__.py
  art/attacks/evasion/geometric_decision_based_attack.py
  tests/attacks/evasion/test_geometric_decision_based_attack.py
Labels: attack, enhancement

#1132 Attribute inference attack that uses membership inference attack
  art/attacks/attack.py
  art/attacks/inference/attribute_inference/__init__.py
  art/attacks/inference/attribute_inference/baseline.py
  art/attacks/inference/attribute_inference/black_box.py
  art/attacks/inference/attribute_inference/meminf_based.py
  art/attacks/inference/attribute_inference/white_box_decision_tree.py
  art/attacks/inference/attribute_inference/white_box_lifestyle_decision_tree.py
  art/attacks/inference/membership_inference/black_box.py
  art/attacks/inference/membership_inference/black_box_rule_based.py
  art/attacks/inference/membership_inference/label_only_boundary_distance.py
  tests/attacks/inference/attribute_inference/test_meminf_based.py
  tests/attacks/inference/membership_inference/test_black_box.py
  tests/attacks/inference/membership_inference/test_black_box_rule_based.py
  tests/attacks/inference/membership_inference/test_label_only_boundary_distance.py
  tests/utils.py
Labels: enhancement

#990 Fixes Bug in Pixel Attack and Threshold Attack.
  art/attacks/evasion/pixel_threshold.py
  tests/attacks/test_pixel_attack.py
  tests/attacks/test_threshold_attack.py
Labels: bug, improvement

#1118 Support for Binary Classification with PGD
  AUTHORS
  art/attacks/evasion/fast_gradient.py
  art/attacks/inference/attribute_inference/meminf_based.py
  art/attacks/inference/membership_inference/black_box.py
  art/estimators/classification/classifier.py
  art/estimators/classification/keras.py
  art/estimators/classification/pytorch.py
  art/estimators/classification/tensorflow.py
  art/utils.py
  tests/attacks/inference/attribute_inference/test_meminf_based.py
  tests/attacks/inference/membership_inference/test_black_box.py
  tests/classifiersFrameworks/test_pytorch.py
  tests/classifiersFrameworks/test_tensorflow.py
  tests/estimators/classification/test_detector_classifier.py
  tests/test_utils.py
  tests/utils.py
Labels: enhancement

#1036 Add PyTorchEspresso estimator to support Espresso models for ASR
  AUTHORS
  art/attacks/evasion/fast_gradient.py
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
  art/estimators/speech_recognition/__init__.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
  art/estimators/speech_recognition/pytorch_espresso.py
Labels: enhancement

#1156 Add support for multiple layers in Feature Adversaries
  art/attacks/evasion/feature_adversaries/feature_adversaries_pytorch.py
  art/attacks/evasion/feature_adversaries/feature_adversaries_tensorflow.py
  tests/attacks/evasion/feature_adversaries/test_feature_adversaries.py
  tests/attacks/evasion/feature_adversaries/test_feature_adversaries_pytorch.py
  tests/attacks/evasion/feature_adversaries/test_feature_adversaries_tensorflow.py
Labels: improvement

#1154 General maintenance updates for ART 1.7.0
  .gitignore
  art/__init__.py
  art/attacks/evasion/auto_projected_gradient_descent.py
  art/attacks/evasion/boundary.py
  art/attacks/evasion/brendel_bethge.py
  art/attacks/evasion/carlini.py
  art/attacks/evasion/deepfool.py
  art/attacks/evasion/elastic_net.py
  art/attacks/evasion/feature_adversaries/feature_adversaries_pytorch.py
  art/attacks/evasion/frame_saliency.py
  art/attacks/evasion/geometric_decision_based_attack.py
  art/attacks/evasion/hop_skip_jump.py
  art/attacks/evasion/newtonfool.py
  art/attacks/evasion/pixel_threshold.py
  art/attacks/evasion/saliency_map.py
  art/attacks/evasion/shadow_attack.py
  art/attacks/evasion/simba.py
  art/attacks/evasion/spatial_transformation.py
  art/attacks/evasion/square_attack.py
  art/attacks/evasion/targeted_universal_perturbation.py
  art/attacks/evasion/universal_perturbation.py
  art/attacks/evasion/virtual_adversarial.py
  art/attacks/evasion/wasserstein.py
  art/attacks/evasion/zoo.py
  art/classifiers/__init__.py
  art/estimators/classification/pytorch.py
  art/estimators/classification/tensorflow.py
  art/wrappers/__init__.py
  art/wrappers/expectation.py
  art/wrappers/query_efficient_bb.py
  conftest.py
  docs/conf.py
  docs/modules/attacks/evasion.rst
  docs/modules/attacks/inference/attribute_inference.rst
  docs/modules/estimators/speech_recognition.rst
  setup.py
Labels: improvement

#1175 Minor bug of Dtype casting in Pixel and Threshold Attack
  art/attacks/evasion/pixel_threshold.py
Labels: improvement

#1173 Fix shuffling of test data in infer (#1165)
  art/attacks/inference/membership_inference/black_box.py
  tests/attacks/inference/attribute_inference/test_meminf_based.py
Labels: bug, improvement

#1181 Add back apply_fit and apply_predict check for Numpy-based preprocessing
  art/estimators/pytorch.py
  art/estimators/tensorflow.py
Labels: bug, improvement

#1189 Fix bugs in Spectral Signature Defense
  art/defences/detector/poison/spectral_signature_defense.py
  art/utils.py
Labels: bug, improvement

#1182 Fix get_started_keras
  art/estimators/classification/keras.py
  examples/get_started_keras.py
  tests/estimators/classification/test_input_filter.py
Labels: improvement
