Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2021-04, with the labels that each got.

#1009 Fix channels_first in perturbation function
  art/attacks/poisoning/perturbations/image_perturbations.py
Labels: bug, improvement

#1002 Implement the estimate gradient function for the FIR filter
  art/preprocessing/audio/l_filter/numpy.py
  art/preprocessing/audio/l_filter/pytorch.py
  tests/preprocessing/audio/test_l_filter.json
  tests/preprocessing/audio/test_l_filter.py
Labels: improvement

#995 Fix bug in elastic net attack
  art/attacks/evasion/elastic_net.py
  tests/attacks/test_elastic_net.py
Labels: bug, improvement

#1010 Add labels to preprocessing in TensorFlowV2Classifier.loss_gradient
  art/estimators/classification/tensorflow.py
Labels: bug, improvement

#1011 Fix return of TensorFlowV2Classifier.get_activations
  art/estimators/classification/tensorflow.py
  tests/attacks/test_hop_skip_jump.py
  tests/estimators/classification/test_deeplearning_common.py
Labels: bug, improvement

#1037 Add check for valid parameters in SimBA
  art/attacks/evasion/simba.py
Labels: improvement

#1035 Create a test environment for deepspeech version2 on github
  .github/actions/deepspeech-v2/Dockerfile
  .github/actions/deepspeech-v2/action.yml
  .github/actions/deepspeech-v2/run.sh
  .github/workflows/ci-deepspeech-v2.yml
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
  art/preprocessing/audio/l_filter/numpy.py
  art/preprocessing/audio/l_filter/pytorch.py
  tests/attacks/evasion/test_imperceptible_asr_pytorch.json
  tests/attacks/evasion/test_imperceptible_asr_pytorch.py
  tests/estimators/speech_recognition/test_pytorch_deep_speech.json
  tests/estimators/speech_recognition/test_pytorch_deep_speech.py
  tests/preprocessing/audio/test_l_filter_pytorch.py
Labels: bug, tests

#1051 Add notebook for EoT of rotation in image classification
  notebooks/README.md
  notebooks/expectation_over_transformation_classification_rotation.ipynb
Labels: enhancement

#1046 Fix a bug in bullseye polytope attack when attacking multiple layers of the underlying model
  art/attacks/poisoning/bullseye_polytope_attack.py
Labels: bug, improvement

#1050 Add tests for PyTorchFasterRCNN
  .github/actions/deepspeech-v2/action.yml
  .github/workflows/ci-deepspeech-v2.yml
  .github/workflows/ci-lingvo.yml
  .github/workflows/ci-mxnet.yml
  .github/workflows/ci-pytorch-fasterrcnn.yml
  .github/workflows/ci.yml
  run_tests.sh
  tests/estimators/object_detection/test_pytorch_faster_rcnn.py
Labels: tests

#1049 Updates for DPatch fixing patch updating
  art/attacks/evasion/dpatch.py
Labels: bug, improvement

#1054 Update get_activations of TensorFlowV2Classifier
  art/estimators/classification/tensorflow.py
Labels: bug, improvement

#748 Update Poisoning Attack Test Infrastructure
  art/attacks/poisoning/perturbations/image_perturbations.py
  run_tests.sh
  tests/attacks/poison/test_adversarial_embedding.py
  tests/attacks/poison/test_backdoor_attack.py
  tests/attacks/poison/test_feature_collision.py
  tests/attacks/poison/test_poisoning_attack_svm.py
  tests/attacks/test_adversarial_embedding.py
  tests/attacks/test_poisoning_attack_svm.py
Labels: tests

#757 Update Poisoning Defense Test Infrastructure
  art/defences/detector/poison/activation_defence.py
  art/defences/detector/poison/clustering_analyzer.py
  art/defences/detector/poison/ground_truth_evaluator.py
  run_tests.sh
  tests/defences/detector/poison/test_activation_defence.py
  tests/defences/detector/poison/test_clustering_analyzer.py
  tests/defences/detector/poison/test_ground_truth_evaluator.py
  tests/defences/detector/poison/test_provenance_defence.py
  tests/defences/detector/poison/test_roni.py
  tests/defences/transformer/poisoning/test_neural_cleanse.py
Labels: tests

#815 #580 evasion tests integration D
  run_tests.sh
  tests/attacks/evasion/test_simba.py
  tests/attacks/evasion/test_targeted_universal_perturbation.py
  tests/attacks/evasion/test_wasserstein.py
  tests/attacks/test_simba.py
  tests/attacks/test_targeted_universal_perturbation.py
  tests/attacks/test_wasserstein.py
Labels: tests

#1065 Fix ScikitlearnLogisticRegression.loss_gradient
  .github/workflows/ci.yml
  art/estimators/classification/scikitlearn.py
  tests/estimators/classification/test_scikitlearn.py
Labels: bug, improvement

#1066 Updates for warnings from dependencies and CI log optimisations
  .github/workflows/ci-mxnet.yml
  .github/workflows/ci-style-checks.yml
  .github/workflows/ci.yml
  art/attacks/evasion/iterative_method.py
  art/defences/detector/poison/ground_truth_evaluator.py
  art/estimators/classification/blackbox.py
  art/estimators/classification/pytorch.py
  art/estimators/classification/scikitlearn.py
  art/metrics/gradient_check.py
  art/metrics/metrics.py
  art/metrics/verification_decisions_trees.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/zoom_blur/pytorch.py
  conftest.py
  tests/attacks/evasion/test_auto_projected_gradient_descent.py
  tests/attacks/evasion/test_boundary.py
  tests/attacks/evasion/test_dpatch_robust.py
  tests/attacks/evasion/test_fast_gradient.py
  tests/attacks/evasion/test_shadow_attack.py
  tests/attacks/evasion/test_square_attack.py
  tests/attacks/poison/test_bullseye_polytope_attack.py
  tests/attacks/test_adversarial_patch.py
  tests/attacks/test_carlini.py
  tests/attacks/test_decision_tree_attack.py
  tests/attacks/test_deepfool.py
  tests/attacks/test_elastic_net.py
  tests/attacks/test_hclu.py
  tests/attacks/test_hop_skip_jump.py
  tests/attacks/test_input_filter.py
  tests/attacks/test_iterative_method.py
  tests/attacks/test_knockoff_nets.py
  tests/attacks/test_newtonfool.py
  tests/attacks/test_pixel_attack.py
  tests/attacks/test_projected_gradient_descent.py
  tests/attacks/test_saliency_map.py
  tests/attacks/test_simba.py
  tests/attacks/test_spatial_transformation.py
  tests/attacks/test_targeted_universal_perturbation.py
  tests/attacks/test_threshold_attack.py
  tests/attacks/test_universal_perturbation.py
  tests/attacks/test_virtual_adversarial.py
  tests/attacks/test_wasserstein.py
  tests/attacks/test_zoo.py
  tests/defences/detector/poison/test_provenance_defence.py
  tests/estimators/classification/test_deeplearning_common.py
  tests/metrics/test_gradient_check.py
  tests/metrics/test_metrics.py
  tests/metrics/test_verification_decision_trees.py
  tests/preprocessing/audio/test_l_filter.py
  tests/preprocessing/audio/test_l_filter_pytorch.py
Labels: improvement
