Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2021-05, with the labels that each got.

#1076 Add missing to device transfer
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
Labels: bug, improvement

#1063 LowProFool, imperceptible attack on tabular data
  AUTHORS
  art/attacks/evasion/__init__.py
  art/attacks/evasion/lowprofool.py
  notebooks/imperceptible_attack_on_tabular_data.ipynb
  tests/attacks/evasion/test_lowprofool.py
Labels: attack, enhancement

#1097 Fix failing download of Iris dataset in tests
  art/utils.py
  tests/attacks/inference/attribute_inference/test_black_box.py
  tests/attacks/test_elastic_net.py
  tests/estimators/classification/test_scikitlearn.py
  tests/test_utils.py
Labels: improvement

#1077 Over The Air Flickering Evasion Attack
  AUTHORS
  art/attacks/evasion/over_the_air_flickering.py
  tests/attacks/test_over_the_air.py
Labels: RCOS project, enhancement

#1052 Generalize DeepSpeech estimator and asr attack to support espresso
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
  art/estimators/speech_recognition/speech_recognizer.py
Labels: improvement

#844 Implementation of Carlini&Wagner's L0 optimized attack
  art/attacks/evasion/__init__.py
  art/attacks/evasion/carlini.py
Labels: enhancement

#1109 Implementation of Carlini&Wagner's L0 optimized attack
  AUTHORS
  art/attacks/evasion/__init__.py
  art/attacks/evasion/carlini.py
Labels: enhancement

#1107 Implement support for deepspeech v3 in ASR attack and Deepspeech estimator
  .github/actions/deepspeech-v3/Dockerfile
  .github/actions/deepspeech-v3/action.yml
  .github/actions/deepspeech-v3/run.sh
  .github/workflows/ci-deepspeech-v3.yml
  art/estimators/speech_recognition/pytorch_deep_speech.py
  tests/attacks/evasion/test_imperceptible_asr_pytorch.py
  tests/estimators/speech_recognition/test_pytorch_deep_speech.json
  tests/estimators/speech_recognition/test_pytorch_deep_speech.py
Labels: enhancement, tests

#1115 Update import version check for suffixes like +cu102
  art/attacks/evasion/adversarial_patch/adversarial_patch_pytorch.py
Labels: improvement

#1116 Update setup.py
  .github/workflows/ci-style-checks.yml
  art/evaluations/security_curve/security_curve.py
  setup.py
Labels: improvement

#1069 Add targeted option to RobustDPatch and fix object detection label formats
  art/attacks/evasion/dpatch.py
  art/attacks/evasion/dpatch_robust.py
  art/estimators/object_detection/object_detector.py
  art/estimators/object_detection/pytorch_faster_rcnn.py
  art/estimators/object_detection/tensorflow_faster_rcnn.py
  art/estimators/object_detection/utils.py
  tests/attacks/evasion/test_dpatch_robust.py
  tests/estimators/object_detection/test_tensorflow_faster_rcnn.py
Labels: improvement

#1102 Over The Air Flickering Evasion Attack
  AUTHORS
  art/attacks/evasion/__init__.py
  art/attacks/evasion/over_the_air_flickering/__init__.py
  art/attacks/evasion/over_the_air_flickering/over_the_air_flickering_pytorch.py
  tests/attacks/evasion/test_over_the_air.py
Labels: enhancement

#1124 Check for NaN in HopSkipJump
  art/attacks/evasion/hop_skip_jump.py
Labels: improvement

#1071 Add TensorBoard support
  art/attacks/attack.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_pytorch.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_tensorflow.py
  art/attacks/evasion/fast_gradient.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_numpy.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_tensorflow_v2.py
  art/estimators/classification/pytorch.py
  art/estimators/classification/tensorflow.py
  art/estimators/object_detection/pytorch_faster_rcnn.py
  art/estimators/object_detection/tensorflow_faster_rcnn.py
  requirements.txt
Labels: enhancement

#1015 Adversarial Attack on PE malware
  Dockerfile
  art/attacks/evasion/__init__.py
  art/attacks/evasion/pe_malware_attack.py
  requirements.txt
  tests/attacks/evasion/test_pe_malware_attack.py
  tests/attacks/utils.py
Labels: attack, enhancement

#419 Fix a small pydub workaround in the MP3 compression preprocessor
  art/defences/preprocessor/mp3_compression.py
  tests/defences/preprocessor/test_mp3_compression.py
Labels: improvement

#1127 Add user-defined loss and adversarial criterium to SquareAttack
  AUTHORS
  art/attacks/evasion/square_attack.py
  tests/attacks/evasion/test_square_attack.py
Labels: enhancement
