Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2021-02, with the labels that each got.

#879 Update numpy version to avoid error
  .github/workflows/ci.yml
  requirements.txt
Labels: improvement

#849 Update BlackboxClassifier
  art/attacks/evasion/simba.py
  art/attacks/evasion/square_attack.py
  art/estimators/classification/__init__.py
  art/estimators/classification/blackbox.py
  docs/modules/estimators/classification.rst
  tests/attacks/evasion/test_square_attack.py
  tests/attacks/test_simba.py
Labels: improvement

#857 Add missing params to estimator_params in sub-classes
  art/attacks/evasion/auto_projected_gradient_descent.py
  art/attacks/inference/membership_inference/black_box.py
  art/attacks/poisoning/adversarial_embedding_attack.py
  art/defences/detector/evasion/detector.py
  art/defences/detector/evasion/subsetscanning/detector.py
  art/defences/preprocessor/inverse_gan.py
  art/estimators/certification/randomized_smoothing/numpy.py
  art/estimators/certification/randomized_smoothing/pytorch.py
  art/estimators/certification/randomized_smoothing/tensorflow.py
  art/estimators/classification/blackbox.py
  art/estimators/classification/catboost.py
  art/estimators/classification/classifier.py
  art/estimators/classification/detector_classifier.py
  art/estimators/classification/ensemble.py
  art/estimators/classification/keras.py
  art/estimators/classification/mxnet.py
  art/estimators/classification/pytorch.py
  art/estimators/classification/tensorflow.py
  art/estimators/classification/xgboost.py
  art/estimators/encoding/tensorflow.py
  art/estimators/estimator.py
  art/estimators/generation/tensorflow.py
  art/estimators/keras.py
  art/estimators/mxnet.py
  art/estimators/object_detection/pytorch_faster_rcnn.py
  art/estimators/object_detection/tensorflow_faster_rcnn.py
  art/estimators/poison_mitigation/neural_cleanse/keras.py
  art/estimators/pytorch.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
  art/estimators/speech_recognition/tensorflow_lingvo.py
  art/estimators/tensorflow.py
  tests/attacks/test_wasserstein.py
  tests/estimators/classification/test_classifier.py
Labels: improvement

#868 Add numba as dependency and apply in BrendelBethgeAttack
  art/attacks/evasion/brendel_bethge.py
  requirements.txt
  setup.py
Labels: improvement

#878 Updates for Adversarial Patch attack in TensorFlow
  art/attacks/evasion/adversarial_patch/adversarial_patch_tensorflow.py
  tests/attacks/test_adversarial_patch.py
Labels: improvement

#877 Define dtype in SquareAttack with norm=2
  art/attacks/evasion/square_attack.py
  tests/attacks/evasion/test_square_attack.py
Labels: improvement

#880 Add backward compatibility for TensorFlow v2 to v1
  .github/workflows/ci.yml
  art/estimators/encoding/tensorflow.py
  art/estimators/generation/tensorflow.py
  art/estimators/object_detection/tensorflow_faster_rcnn.py
  examples/get_started_tensorflow.py
  tests/defences/preprocessor/test_spatial_smoothing_tensorflow.py
  tests/defences/test_adversarial_trainer_FBF.py
  tests/estimators/classification/test_deeplearning_specific.py
  tests/estimators/speech_recognition/test_pytorch_deep_speech.py
  tests/metrics/test_metrics.py
  tests/preprocessing/audio/test_l_filter_pytorch.py
  tests/utils.py
Labels: improvement

#887 Update numpy requirements
  requirements.txt
  setup.py
Labels: improvement

#886 Fix float issue for security_curve.py
  art/evaluations/security_curve/security_curve.py
Labels: improvement

#890 Define dtype in StandardisationMeanStdPyTorch
  art/preprocessing/standardisation_mean_std/standardisation_mean_std_pytorch.py
Labels: improvement

#898 [897] updated import membership inference import statements in attack…
  notebooks/attack_membership_inference.ipynb
Labels: improvement, notebooks

#900 899 updated MembershipInferenceBlackBox#infer to have CUDA support
  art/attacks/inference/membership_inference/black_box.py
  art/utils.py
Labels: bug

#901 Update set_params in BaseEstimator
  art/estimators/estimator.py
  art/estimators/pytorch.py
  art/estimators/tensorflow.py
  tests/classifiersFrameworks/test_pytorch.py
  tests/classifiersFrameworks/test_tensorflow.py
  tests/estimators/classification/test_blackbox.py
  tests/estimators/classification/test_classifier.py
  tests/estimators/classification/test_deeplearning_common.json
  tests/estimators/classification/test_detector_classifier.py
  tests/estimators/classification/test_ensemble.py
Labels: improvement

#869 Remove deprecated channel_index argument
  .github/workflows/ci.yml
  art/attacks/evasion/dpatch.py
  art/defences/detector/evasion/detector.py
  art/defences/detector/evasion/subsetscanning/detector.py
  art/defences/preprocessor/jpeg_compression.py
  art/defences/preprocessor/mp3_compression.py
  art/defences/preprocessor/resample.py
  art/defences/preprocessor/spatial_smoothing.py
  art/defences/preprocessor/thermometer_encoding.py
  art/estimators/classification/detector_classifier.py
  art/estimators/classification/ensemble.py
  art/estimators/classification/keras.py
  art/estimators/classification/mxnet.py
  art/estimators/classification/pytorch.py
  art/estimators/classification/tensorflow.py
  art/estimators/estimator.py
  art/estimators/object_detection/pytorch_faster_rcnn.py
  tests/estimators/classification/test_classifier.py
  tests/estimators/classification/test_deeplearning_common.json
  tests/estimators/classification/test_deeplearning_common.py
  tests/estimators/classification/test_deeplearning_specific.py
  tests/estimators/classification/test_ensemble.py
Labels: improvement

#906 Update to ART 1.5.2
  .github/workflows/ci.yml
  art/__init__.py
  art/attacks/evasion/__init__.py
  art/attacks/evasion/adversarial_patch/adversarial_patch.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_numpy.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_tensorflow.py
  art/attacks/evasion/auto_attack.py
  art/attacks/evasion/auto_projected_gradient_descent.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_tensorflow_v2.py
  art/attacks/evasion/saliency_map.py
  art/attacks/evasion/shadow_attack.py
  art/attacks/evasion/simba.py
  art/attacks/evasion/square_attack.py
  art/attacks/inference/membership_inference/black_box.py
  art/estimators/classification/__init__.py
  art/estimators/classification/blackbox.py
  art/estimators/classification/pytorch.py
  art/estimators/estimator.py
  art/estimators/pytorch.py
  art/estimators/tensorflow.py
  art/evaluations/security_curve/security_curve.py
  art/preprocessing/standardisation_mean_std/standardisation_mean_std_pytorch.py
  art/utils.py
  docs/conf.py
  docs/modules/estimators/classification.rst
  tests/attacks/evasion/test_square_attack.py
  tests/attacks/test_simba.py
  tests/classifiersFrameworks/test_pytorch.py
  tests/classifiersFrameworks/test_tensorflow.py
  tests/estimators/classification/test_blackbox.py
  tests/estimators/classification/test_classifier.py
  tests/estimators/classification/test_deeplearning_common.json
  tests/estimators/classification/test_detector_classifier.py
  tests/estimators/classification/test_ensemble.py
Labels: release

#914 Use spectrogram in PSD transform of ASR attack
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
Labels: improvement

#858 PDTP Privacy metric
  art/defences/detector/evasion/detector.py
  art/defences/detector/evasion/subsetscanning/detector.py
  art/estimators/certification/randomized_smoothing/numpy.py
  art/estimators/classification/GPy.py
  art/estimators/classification/blackbox.py
  art/estimators/classification/catboost.py
  art/estimators/classification/detector_classifier.py
  art/estimators/classification/ensemble.py
  art/estimators/classification/keras.py
  art/estimators/classification/lightgbm.py
  art/estimators/classification/mxnet.py
  art/estimators/classification/pytorch.py
  art/estimators/classification/scikitlearn.py
  art/estimators/classification/tensorflow.py
  art/estimators/classification/xgboost.py
  art/estimators/encoding/tensorflow.py
  art/estimators/estimator.py
  art/estimators/generation/tensorflow.py
  art/estimators/object_detection/object_detector.py
  art/estimators/object_detection/pytorch_faster_rcnn.py
  art/estimators/object_detection/tensorflow_faster_rcnn.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
  art/estimators/speech_recognition/tensorflow_lingvo.py
  art/metrics/__init__.py
  art/metrics/privacy/__init__.py
  art/metrics/privacy/membership_leakage.py
  art/wrappers/expectation.py
  art/wrappers/query_efficient_bb.py
  run_tests.sh
  tests/attacks/evasion/conftest.py
  tests/attacks/evasion/test_dpatch_robust.py
  tests/attacks/test_wasserstein.py
  tests/estimators/classification/test_classifier.py
  tests/metrics/privacy/__init__.py
  tests/metrics/privacy/test_membership_leakage.py
Labels: enhancement

#918 Architecture updates for PDTP
  art/estimators/classification/pytorch.py
  art/estimators/classification/scikitlearn.py
  art/estimators/classification/tensorflow.py
  art/metrics/__init__.py
  art/metrics/privacy/__init__.py
  art/metrics/privacy/membership_leakage.py
  run_tests.sh
  tests/metrics/privacy/__init__.py
  tests/metrics/privacy/test_membership_leakage.py
Labels: improvement

#916 Return None in BaseEstimator._set_preprocessing for None input
  art/estimators/estimator.py
Labels: improvement

#917 Reset adaptive optimizers per batch in ASR attack
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
Labels: bug

#891 Implement method to apply adversarial patch onto a real-world surface
  AUTHORS
  art/attacks/evasion/adversarial_patch/adversarial_patch.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_numpy.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_tensorflow.py
  art/attacks/evasion/adversarial_patch/utils.py
  requirements.txt
  tests/attacks/test_adversarial_patch.py
Labels: enhancement
