Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2021-07, with the labels that each got.

#1201 Support for video compression defence in PyTorch-specific attacks
  art/defences/preprocessor/__init__.py
  art/defences/preprocessor/video_compression_pytorch.py
Labels: improvement

#1209 Add non-framework install option
  setup.py
Labels: dependencies

#1207 feature_adversaries_numpy.py
  requirements.txt
Labels: enhancement

#1198 ASR attack supports batch size larger than 1
  .github/actions/deepspeech-v2/run.sh
  .github/actions/deepspeech-v3/run.sh
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
  notebooks/asr_deepspeech_examples.ipynb
  tests/attacks/evasion/test_imperceptible_asr_pytorch.py
Labels: bug

#1210 Pytorch wrapper MP3 defense
  art/defences/preprocessor/__init__.py
  art/defences/preprocessor/mp3_compression.py
  art/defences/preprocessor/mp3_compression_pytorch.py
Labels: improvement

#1219 Remove duplicate application of preprocessing in fallback BaseEstimator.fit_generator
  art/estimators/estimator.py
Labels: bug, improvement

#1223 Fix device_type of default preprocessor of PyTorchEstimator
  art/estimators/pytorch.py
Labels: bug, improvement

#1218 Update to ART 1.7.1
  .github/actions/deepspeech-v2/run.sh
  .github/actions/deepspeech-v3/run.sh
  art/__init__.py
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
  art/attacks/evasion/over_the_air_flickering/over_the_air_flickering_pytorch.py
  art/attacks/evasion/pixel_threshold.py
  art/attacks/inference/membership_inference/black_box.py
  art/defences/detector/poison/spectral_signature_defense.py
  art/defences/preprocessor/__init__.py
  art/defences/preprocessor/mp3_compression.py
  art/defences/preprocessor/mp3_compression_pytorch.py
  art/defences/preprocessor/video_compression_pytorch.py
  art/estimators/classification/keras.py
  art/estimators/estimator.py
  art/estimators/pytorch.py
  art/estimators/tensorflow.py
  art/utils.py
  docs/conf.py
  examples/get_started_keras.py
  notebooks/asr_deepspeech_examples.ipynb
  setup.py
  tests/attacks/evasion/test_imperceptible_asr_pytorch.py
  tests/attacks/inference/attribute_inference/test_meminf_based.py
  tests/estimators/classification/test_input_filter.py
Labels: release
