Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2021-08, with the labels that each got.

#1208 Create a test environment for Tensorflow object detector
  .github/actions/tf-faster-rcnn/Dockerfile
  .github/actions/tf-faster-rcnn/action.yml
  .github/actions/tf-faster-rcnn/run.sh
  .github/workflows/ci-tf-faster-rcnn.yml
  tests/estimators/object_detection/test_tensorflow_faster_rcnn.py
Labels: tests

#1264 Add missing support for index labels
  art/estimators/classification/pytorch.py
Labels: improvement

#1261 Add patched Lingvo decoder to contrib folder
  .github/workflows/ci-style-checks.yml
  art/estimators/speech_recognition/tensorflow_lingvo.py
  contrib/lingvo-patched-decoder.py
Labels: improvement

#1262 Fix min_epsilon of BoundaryAttack to receive a non-negative value
  art/attacks/evasion/boundary.py
Labels: bug, improvement

#1197 New boundary attack
  art/attacks/inference/membership_inference/label_only_boundary_distance.py
  notebooks/label_only_membership_inference.ipynb
  tests/attacks/inference/membership_inference/test_label_only_boundary_distance.py
Labels: enhancement

#1265 Update component.yaml to kfp v2 sdk
  utils/mlops/kubeflow/robustness_evaluation_fgsm_pytorch/component.yaml
Labels: improvement

#1290 Getting the shape from the correct matrix (Fixing issue #1289)
  art/attacks/poisoning/perturbations/image_perturbations.py
Labels: bug, improvement
