Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2021-09, with the labels that each got.

#1247 Extend BlackBoxClassifier* to accept existing predictions
  art/estimators/classification/blackbox.py
  notebooks/README.md
  notebooks/classifier_blackbox_lookup_table.ipynb
  requirements.txt
  run_tests.sh
  setup.py
  tests/estimators/classification/test_blackbox_existing_predictions.py
Labels: enhancement

#1256 Remove art.classifiers and art.wrappers
  art/classifiers/__init__.py
  art/classifiers/scikitlearn/__init__.py
  art/estimators/classification/__init__.py
  art/estimators/classification/blackbox.py
  art/estimators/classification/catboost.py
  art/estimators/classification/detector_classifier.py
  art/estimators/classification/lightgbm.py
  art/estimators/classification/mxnet.py
  art/estimators/classification/query_efficient_bb.py
  art/estimators/classification/scikitlearn.py
  art/estimators/classification/xgboost.py
  art/utils.py
  art/wrappers/__init__.py
  art/wrappers/expectation.py
  art/wrappers/wrapper.py
  docs/index.rst
  docs/modules/estimators/classification.rst
  docs/modules/wrappers.rst
  notebooks/imperceptible_attack_on_tabular_data.ipynb
  run_tests.sh
  tests/estimators/classification/test_query_efficient_bb.py
  tests/test_data_generators.py
  tests/wrappers/__init__.py
  tests/wrappers/test_expectation.py
  tests/wrappers/test_wrapper.py
Labels: improvement

#1295 Add general object detection estimator for PyTorch
  .github/workflows/ci-pytorch-object-detectors.yml
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent.py
  art/estimators/object_detection/__init__.py
  art/estimators/object_detection/python_object_detector.py
  art/estimators/object_detection/pytorch_faster_rcnn.py
  art/utils.py
  examples/application_object_detection.py
  tests/estimators/object_detection/test_pytorch_faster_rcnn.py
  tests/estimators/object_detection/test_pytorch_object_detector.py
Labels: enhancement

#1310 Fix error in membership attack notebook
  notebooks/attack_membership_inference.ipynb
Labels: improvement, notebooks

#1312 fix import error at model inversion attacks notebook
  notebooks/model_inversion_attacks_mnist.ipynb
Labels: improvement, notebooks

#1320 Update CI base images
  .github/workflows/ci-legacy.yml
  .github/workflows/ci-mxnet.yml
  tests/attacks/test_hclu.py
Labels: tests

#1319 Development documentation
  art/attacks/attack.py
  art/attacks/evasion/brendel_bethge.py
  docs/modules/attacks/evasion.rst
  tests/attacks/test_input_filter.py
  tests/attacks/test_pixel_attack.py
Labels: documentation

#1318 Add estimator for object tracker GOTURN in PyTorch
  .github/actions/goturn/Dockerfile
  .github/actions/goturn/action.yml
  .github/actions/goturn/run.sh
  .github/workflows/ci-goturn.yml
  art/attacks/evasion/fast_gradient.py
  art/estimators/object_tracking/__init__.py
  art/estimators/object_tracking/object_tracker.py
  art/estimators/object_tracking/pytorch_goturn.py
  examples/get_started_pytorch_goturn.py
  tests/estimators/object_tracking/__init__.py
  tests/estimators/object_tracking/test_pytorch_goturn.py
Labels: enhancement

#1333 Update documentation and fix cuda device support in AdversarialPatchPyTorch
  art/attacks/evasion/adversarial_patch/adversarial_patch_pytorch.py
Labels: bug, improvement
