Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2021-11, with the labels that each got.

#1345 Shadow model training
  art/attacks/inference/membership_inference/__init__.py
  art/attacks/inference/membership_inference/black_box.py
  art/attacks/inference/membership_inference/shadow_models.py
  art/defences/detector/evasion/detector.py
  art/defences/detector/evasion/subsetscanning/detector.py
  art/estimators/certification/randomized_smoothing/numpy.py
  art/estimators/classification/GPy.py
  art/estimators/classification/blackbox.py
  art/estimators/classification/catboost.py
  art/estimators/classification/classifier.py
  art/estimators/classification/detector_classifier.py
  art/estimators/classification/ensemble.py
  art/estimators/classification/keras.py
  art/estimators/classification/lightgbm.py
  art/estimators/classification/mxnet.py
  art/estimators/classification/pytorch.py
  art/estimators/classification/scikitlearn.py
  art/estimators/classification/tensorflow.py
  art/estimators/estimator.py
  notebooks/README.md
  notebooks/attack_membership_inference_shadow_models.ipynb
  tests/attacks/evasion/test_pe_malware_attack.py
  tests/attacks/inference/membership_inference/test_shadow_models.py
  tests/attacks/test_wasserstein.py
Labels: enhancement

#1395 Introduce shadow model training for inference attacks
  art/attacks/inference/membership_inference/__init__.py
  art/attacks/inference/membership_inference/black_box.py
  art/attacks/inference/membership_inference/shadow_models.py
  art/defences/detector/evasion/detector.py
  art/defences/detector/evasion/subsetscanning/detector.py
  art/estimators/certification/randomized_smoothing/numpy.py
  art/estimators/classification/GPy.py
  art/estimators/classification/blackbox.py
  art/estimators/classification/catboost.py
  art/estimators/classification/classifier.py
  art/estimators/classification/detector_classifier.py
  art/estimators/classification/ensemble.py
  art/estimators/classification/keras.py
  art/estimators/classification/lightgbm.py
  art/estimators/classification/mxnet.py
  art/estimators/classification/pytorch.py
  art/estimators/classification/scikitlearn.py
  art/estimators/classification/tensorflow.py
  art/estimators/estimator.py
  notebooks/README.md
  notebooks/attack_membership_inference_shadow_models.ipynb
  tests/attacks/evasion/test_pe_malware_attack.py
  tests/attacks/inference/membership_inference/test_shadow_models.py
  tests/attacks/test_wasserstein.py
Labels: enhancement

#1380 Updates for CarliniLInfMethod attack
  art/attacks/evasion/carlini.py
  art/optimizers.py
  notebooks/art-for-tensorflow-v2-callable.ipynb
  notebooks/art-for-tensorflow-v2-keras.ipynb
  run_tests.sh
  tests/attacks/test_carlini.py
  tests/test_optimizers.py
Labels: enhancement, improvement

#1423 Remove outdated comments in SimBA tests
  tests/attacks/test_simba.py
Labels: improvement, documentation
