Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2021-03, with the labels that each got.

#912 Fix for changing DeepSpeech states
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
  art/estimators/pytorch.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
Labels: improvement

#876 Implement Adversarial Patch attack in PyTorch.
  art/attacks/evasion/__init__.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_pytorch.py
  art/estimators/classification/pytorch.py
Labels: enhancement

#913 Extend Image Trigger Functionality
  art/attacks/poisoning/clean_label_backdoor_attack.py
  art/attacks/poisoning/perturbations/image_perturbations.py
  notebooks/poisoning_attack_backdoor_image.ipynb
  tests/attacks/test_backdoor_attack.py
Labels: enhancement

#927 Fix black-box attribute attack to support 1-hot-encoded and scaled features
  art/attacks/inference/attribute_inference/black_box.py
  art/utils.py
  tests/attacks/inference/attribute_inference/test_black_box.py
Labels: improvement

#919 EoTs of natural image corruptions
  art/estimators/estimator.py
  art/estimators/pytorch.py
  art/estimators/tensorflow.py
  art/preprocessing/audio/__init__.py
  art/preprocessing/audio/l_filter/numpy.py
  art/preprocessing/audio/l_filter/pytorch.py
  art/preprocessing/expectation_over_transformation/__init__.py
  art/preprocessing/expectation_over_transformation/eot_image_rotation/eot_image_rotation_tensorflow.py
  art/preprocessing/expectation_over_transformation/image_rotation/__init__.py
  art/preprocessing/expectation_over_transformation/image_rotation/tensorflow.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/__init__.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/brightness/__init__.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/brightness/pytorch.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/brightness/tensorflow.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/contrast/__init__.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/contrast/pytorch.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/contrast/tensorflow.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/gaussian_noise/__init__.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/gaussian_noise/pytorch.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/gaussian_noise/tensorflow.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/shot_noise/__init__.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/shot_noise/pytorch.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/shot_noise/tensorflow.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/zoom_blur/__init__.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/zoom_blur/pytorch.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/zoom_blur/tensorflow.py
  art/preprocessing/expectation_over_transformation/pytorch.py
  art/preprocessing/expectation_over_transformation/tensorflow.py
  art/preprocessing/standardisation_mean_std/__init__.py
  art/preprocessing/standardisation_mean_std/numpy.py
  art/preprocessing/standardisation_mean_std/pytorch.py
  art/preprocessing/standardisation_mean_std/tensorflow.py
  docs/modules/preprocessing/standardisation_mean_std.rst
  tests/attacks/test_hop_skip_jump.py
  tests/estimators/classification/test_deeplearning_common.json
  tests/preprocessing/expectation_over_transformation/natural_corruptions/__init__.py
  tests/preprocessing/expectation_over_transformation/natural_corruptions/test_brightness.py
  tests/preprocessing/expectation_over_transformation/natural_corruptions/test_contrast.py
  tests/preprocessing/expectation_over_transformation/natural_corruptions/test_gaussian_noise.py
  tests/preprocessing/expectation_over_transformation/natural_corruptions/test_shot_noise.py
  tests/preprocessing/expectation_over_transformation/natural_corruptions/test_zoom_blur.py
  tests/preprocessing/expectation_over_transformation/test_image_rotation.py
  tests/preprocessing/test_standardisation_mean_std.py
Labels: enhancement

#948 BoundaryAttack: Fixed targeted/untargeted satisfied criterion + return min L2 norm adv. example
  art/attacks/evasion/boundary.py
Labels: improvement

#935 Support for classifiers with no input_shape
  art/attacks/inference/attribute_inference/black_box.py
  art/attacks/inference/membership_inference/black_box.py
  art/attacks/inference/membership_inference/black_box_rule_based.py
  art/estimators/classification/scikitlearn.py
Labels: improvement

#930 Improve Psychoacoustic model and some ASR maintenance
  art/attacks/evasion/adversarial_asr.py
  art/attacks/evasion/imperceptible_asr/imperceptible_asr.py
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
  art/estimators/speech_recognition/tensorflow_lingvo.py
  art/utils.py
  requirements.txt
  tests/attacks/evasion/test_imperceptible_asr.py
Labels: improvement

#931 Cast type of asr attack to float64 to fix the NaN issue
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
  tests/attacks/evasion/test_imperceptible_asr_pytorch.py
Labels: improvement

#954 Protect labels from overwriting in PyTorchFasterRCNN.loss_gradient
  art/estimators/object_detection/pytorch_faster_rcnn.py
Labels: improvement

#959 Update parameters CarliniWagnerASR attack
  art/attacks/evasion/adversarial_asr.py
Labels: improvement

#955 Align parameter names in ASR attacks
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
  tests/attacks/evasion/test_imperceptible_asr_pytorch.py
Labels: improvement

#839 Ensure that mean and standard deviation are broadcastable in standardization preprocessors
  art/estimators/certification/randomized_smoothing/pytorch.py
  art/estimators/certification/randomized_smoothing/tensorflow.py
  art/estimators/classification/GPy.py
  art/estimators/classification/blackbox.py
  art/estimators/classification/catboost.py
  art/estimators/classification/detector_classifier.py
  art/estimators/classification/ensemble.py
  art/estimators/classification/keras.py
  art/estimators/classification/lightgbm.py
  art/estimators/classification/mxnet.py
  art/estimators/classification/pytorch.py
  art/estimators/classification/scikitlearn.py
  art/estimators/classification/tensorflow.py
  art/estimators/classification/xgboost.py
  art/estimators/encoding/tensorflow.py
  art/estimators/estimator.py
  art/estimators/generation/tensorflow.py
  art/estimators/object_detection/tensorflow_faster_rcnn.py
  art/estimators/poison_mitigation/neural_cleanse/keras.py
  art/preprocessing/standardisation_mean_std/numpy.py
  art/preprocessing/standardisation_mean_std/pytorch.py
  art/preprocessing/standardisation_mean_std/tensorflow.py
  art/preprocessing/standardisation_mean_std/utils.py
  conftest.py
  examples/get_started_mxnet.py
  tests/defences/preprocessor/conftest.py
  tests/estimators/classification/test_blackbox.py
  tests/estimators/classification/test_classifier.py
  tests/estimators/classification/test_deeplearning_common.json
  tests/estimators/classification/test_detector_classifier.py
  tests/estimators/classification/test_ensemble.py
  tests/preprocessing/test_standardisation_mean_std.py
Labels: improvement

#961 Feature/rename skip framework marker
  conftest.py
  run_tests.sh
  setup.cfg
  tests/attacks/evasion/test_adversarial_asr.py
  tests/attacks/evasion/test_auto_attack.py
  tests/attacks/evasion/test_auto_projected_gradient_descent.py
  tests/attacks/evasion/test_brendel_and_bethge.py
  tests/attacks/evasion/test_fast_gradient.py
  tests/attacks/evasion/test_feature_adversaries.py
  tests/attacks/evasion/test_frame_saliency.py
  tests/attacks/evasion/test_imperceptible_asr.py
  tests/attacks/evasion/test_imperceptible_asr_pytorch.py
  tests/attacks/inference/attribute_inference/test_black_box.py
  tests/attacks/inference/attribute_inference/test_white_box_decision_tree.py
  tests/attacks/inference/attribute_inference/test_white_box_lifestyle_decision_tree.py
  tests/attacks/inference/membership_inference/test_black_box.py
  tests/attacks/poison/test_clean_label_backdoor_attack.py
  tests/attacks/utils.py
  tests/defences/detector/poison/test_spectral_signature_defense.py
  tests/defences/preprocessor/test_inverse_gan.py
  tests/defences/preprocessor/test_mp3_compression.py
  tests/defences/preprocessor/test_video_compression.py
  tests/defences/test_adversarial_trainer_FBF.py
  tests/estimators/classification/test_deeplearning_common.py
  tests/estimators/classification/test_deeplearning_specific.py
  tests/estimators/speech_recognition/test_pytorch_deep_speech.py
  tests/estimators/speech_recognition/test_tensorflow_lingvo.py
  tests/metrics/privacy/test_membership_leakage.py
  tests/preprocessing/audio/test_l_filter_pytorch.py
  tests/utils.py
  tests/utils/test_utils.py
Labels: improvement

#956 Add baseline attribute attack
  art/attacks/inference/attribute_inference/__init__.py
  art/attacks/inference/attribute_inference/baseline.py
  notebooks/attack_attribute_inference.ipynb
  tests/attacks/inference/attribute_inference/test_baseline.py
  tests/attacks/inference/attribute_inference/test_black_box.py
Labels: enhancement

#882 Expand range of eps_step and eps in PGD attacks
  art/attacks/evasion/fast_gradient.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_numpy.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_tensorflow_v2.py
Labels: improvement

#883 Check for NaN in loss gradient of PGD attacks and replace with 0.0
  art/attacks/evasion/fast_gradient.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_tensorflow_v2.py
Labels: improvement

#964 Update to ART 1.5.3
  art/__init__.py
  art/attacks/evasion/adversarial_asr.py
  art/attacks/evasion/imperceptible_asr/imperceptible_asr.py
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
  art/estimators/classification/scikitlearn.py
  art/estimators/estimator.py
  art/estimators/object_detection/tensorflow_faster_rcnn.py
  art/estimators/pytorch.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
  art/estimators/speech_recognition/tensorflow_lingvo.py
  art/utils.py
  docs/conf.py
  notebooks/classifier_scikitlearn_SVC_LinearSVC.ipynb
  notebooks/classifier_scikitlearn_pipeline_pca_cv_svc.ipynb
  requirements.txt
  tests/attacks/evasion/test_imperceptible_asr.py
  tests/attacks/evasion/test_imperceptible_asr_pytorch.py
  tests/estimators/classification/test_blackbox.py
  tests/estimators/classification/test_classifier.py
  tests/estimators/classification/test_detector_classifier.py
  tests/estimators/classification/test_scikitlearn.py
Labels: release

#962 Implement Bullseye Polytope Clean Label Attack
  art/attacks/poisoning/__init__.py
  art/attacks/poisoning/bullseye_polytope_attack.py
  art/estimators/classification/classifier.py
  art/estimators/classification/pytorch.py
  docs/modules/attacks/poisoning.rst
  notebooks/poisoning_attack_bullseye_polytope.ipynb
  tests/attacks/poison/test_bullseye_polytope_attack.py
Labels: enhancement

#971 Increase batch_size (set default batch_size=64) in BoundaryAttack and HopSkipJump
  art/attacks/evasion/boundary.py
  art/attacks/evasion/hop_skip_jump.py
Labels: improvement

#988 Catch ValueError and provide explanation for too large nb_parallel
  art/attacks/evasion/zoo.py
Labels: improvement

#987 Upgrade to scikit-learn 0.24
  .github/workflows/ci-mxnet.yml
  .github/workflows/ci.yml
  requirements.txt
  setup.py
  tests/attacks/inference/attribute_inference/test_black_box.py
  tests/attacks/inference/test_reconstruction.py
Labels: improvement

#1000 Update black box classifier
  art/estimators/classification/blackbox.py
  tests/estimators/classification/test_blackbox.py
  tests/utils.py
Labels: bug, improvement

#994 Add compute_loss to PyTorchDeepSpeech and TensorFlowFasterRCNN
  art/estimators/object_detection/tensorflow_faster_rcnn.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
  tests/attacks/test_hop_skip_jump.py
  tests/estimators/object_detection/test_tensorflow_faster_rcnn.py
Labels: bug, improvement
