Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2021-12, with the labels that each got.

#1397 Implement Deep Partition Aggregation
  art/estimators/classification/__init__.py
  art/estimators/classification/deep_partition_ensemble.py
  art/estimators/classification/ensemble.py
  examples/inverse_gan_author_utils.py
  notebooks/README.md
  notebooks/poisoning_defense_deep_partition_aggregation.ipynb
  run_tests.sh
  tests/estimators/classification/test_deep_partition_ensemble.py
Labels: enhancement

#1430 Implement Adversarial Texture Attack on Object Trackers
  .github/actions/goturn/run.sh
  .github/workflows/ci-style-checks.yml
  art/attacks/evasion/__init__.py
  art/attacks/evasion/adversarial_texture/__init__.py
  art/attacks/evasion/adversarial_texture/adversarial_texture_pytorch.py
  conftest.py
  tests/attacks/evasion/test_adversarial_texture_pytorch.py
Labels: enhancement

#1416 Implement customizable summary writer and indicators of attack failure
  art/attacks/attack.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_pytorch.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_tensorflow.py
  art/attacks/evasion/adversarial_texture/adversarial_texture_pytorch.py
  art/attacks/evasion/fast_gradient.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_numpy.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_tensorflow_v2.py
  art/estimators/object_detection/python_object_detector.py
  art/estimators/object_tracking/pytorch_goturn.py
  art/summary_writer.py
  art/utils.py
  conftest.py
  run_tests.sh
  tests/test_summary_writer.py
Labels: enhancement

#1441 Adding type preservation to insert_image
  art/attacks/poisoning/perturbations/image_perturbations.py
Labels: bug, improvement

#1398 add adversarial laser beam attack and tests
  art/attacks/evasion/laser_attack/__init__.py
  art/attacks/evasion/laser_attack/algorithms.py
  art/attacks/evasion/laser_attack/laser_attack.py
  art/attacks/evasion/laser_attack/utils.py
  notebooks/attack_laser.ipynb
  tests/attacks/evasion/test_laser_attack.py
Labels: enhancement

#1422 Add support for multiple samples in SimBA.generate
  art/attacks/evasion/simba.py
Labels: bug, improvement

#1443 Update check_and_transform_label_format for index labels
  art/attacks/evasion/pixel_threshold.py
  art/estimators/classification/keras.py
  art/utils.py
  tests/test_utils.py
Labels: bug, improvement

#1444 Set _device parameter automatically in PreprocessorPyTorch (fixes #1442)
  art/defences/preprocessor/mp3_compression_pytorch.py
  art/defences/preprocessor/preprocessor.py
  art/defences/preprocessor/spatial_smoothing_pytorch.py
  art/defences/preprocessor/video_compression_pytorch.py
  art/preprocessing/audio/l_filter/pytorch.py
  art/preprocessing/standardisation_mean_std/pytorch.py
  tests/defences/preprocessor/test_preprocessor.py
Labels: improvement

#1360 Implement a classifier on Jax framework
  .github/workflows/ci-lingvo.yml
  art/experimental/__init__.py
  art/experimental/estimators/__init__.py
  art/experimental/estimators/classification/__init__.py
  art/experimental/estimators/classification/jax.py
  art/experimental/estimators/jax.py
  art/utils.py
  conftest.py
  requirements_test.txt
  tests/estimators/classification/test_jax.json
  tests/estimators/classification/test_jax.py
Labels: enhancement

#1446 Code maintenance updates for ART 1.9.0
  art/attacks/evasion/__init__.py
  art/attacks/evasion/adversarial_texture/adversarial_texture_pytorch.py
  art/attacks/evasion/laser_attack/algorithms.py
  art/attacks/evasion/laser_attack/laser_attack.py
  art/attacks/evasion/laser_attack/utils.py
  art/attacks/inference/membership_inference/label_only_boundary_distance.py
  art/estimators/object_tracking/__init__.py
  art/estimators/poison_mitigation/__init__.py
  conftest.py
  docs/images/summary_writer_patch.png
  docs/images/summary_writer_scalar.png
  docs/index.rst
  docs/modules/attacks/evasion.rst
  docs/modules/estimators/classification.rst
  docs/modules/estimators/object_detection.rst
  docs/modules/estimators/object_tracking.rst
  docs/modules/estimators/poison_mitigation.rst
  docs/modules/estimators/poison_mitigation_neural_cleanse.rst
  docs/modules/estimators/poison_mitigation_strip.rst
  docs/modules/estimators/regression_scikitlearn.rst
Labels: improvement
