Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2021-01, with the labels that each got.

#810 Fix Keras Import for Custom Loss Gradient
  art/estimators/classification/keras.py
Labels: improvement

#791 Test codecov with GitHub Actions
  .github/workflows/ci.yml
  codecov.yml
Labels: tests

#825 Added an option to use probability values for model stealing. Added a…
  art/attacks/extraction/copycat_cnn.py
  art/attacks/extraction/knockoff_nets.py
  notebooks/README.md
  notebooks/model-stealing-demo.ipynb
Labels: enhancement

#718 Dev 1.5.0 580 evasion tests integration_B
  run_tests.sh
  tests/attacks/evasion/test_threshold_attack.py
  tests/attacks/evasion/test_universal_perturbation.py
  tests/attacks/evasion/test_virtual_adversarial.py
  tests/attacks/test_threshold_attack.py
  tests/attacks/test_universal_perturbation.py
  tests/attacks/test_virtual_adversarial.py
Labels: tests

#834 handle dependencies, eager execution, resnet50 preprocessing
  notebooks/attack_defence_imagenet.ipynb
  notebooks/poisoning_defense_activation_clustering.ipynb
Labels: enhancement

#833 PGD bug fix for targeted attacks in frameworks
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_tensorflow_v2.py
Labels: improvement

#843 Fixing search_space initialization on JSMA
  art/attacks/evasion/saliency_map.py
Labels: improvement

#850 Add passing of kwargs in AutoAttack.generate
  art/attacks/evasion/auto_attack.py
Labels: improvement

#848 Add support in ShadowAttack for channels_first=False in PyTorch
  art/attacks/evasion/shadow_attack.py
Labels: improvement

#827 Add an option to SklearnClassifier to use logits
  art/estimators/classification/scikitlearn.py
Labels: enhancement

#873 Add CarliniWagnerASR to evasion namespace
  art/attacks/evasion/__init__.py
Labels: improvement

#862 Update GPU support for PyTorchClassifier.loss
  art/estimators/classification/pytorch.py
Labels: improvement

#838 Update AdversarialPatchNumpy for video format
  art/attacks/evasion/adversarial_patch/adversarial_patch_numpy.py
Labels: improvement

#860 Update AutoProjectedGradientDescent for targeted attacks
  art/attacks/evasion/auto_projected_gradient_descent.py
Labels: improvement

#863 Add patch reset option to Adversarial Patch attacks
  art/attacks/evasion/adversarial_patch/adversarial_patch.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_numpy.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_tensorflow.py
Labels: improvement
