Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2022-03, with the labels that each got.

#1560 Extend support for TensorFlow v1 compatibility mode
  art/data_generators.py
  art/estimators/classification/tensorflow.py
  conftest.py
  tests/attacks/evasion/feature_adversaries/test_feature_adversaries_tensorflow.py
  tests/attacks/evasion/test_auto_attack.py
  tests/attacks/evasion/test_auto_projected_gradient_descent.py
  tests/estimators/classification/test_deeplearning_common.json
  tests/metrics/privacy/test_membership_leakage.py
  tests/utils.py
Labels: improvement

#1534 Improvements to attribute inference attacks
  art/attacks/inference/attribute_inference/baseline.py
  art/attacks/inference/attribute_inference/black_box.py
  art/attacks/inference/attribute_inference/true_label_baseline.py
  art/utils.py
  notebooks/attack_attribute_inference.ipynb
  notebooks/attack_attribute_inference_regressor.ipynb
  notebooks/label_only_membership_inference.ipynb
  tests/attacks/inference/attribute_inference/test_baseline.py
  tests/attacks/inference/attribute_inference/test_black_box.py
  tests/attacks/inference/attribute_inference/test_true_label_baseline.py
  tests/attacks/inference/attribute_inference/test_white_box_lifestyle_decision_tree.py
Labels: improvement

#1535 Add support for object detection in AdversarialPatchPyTorch
  art/attacks/evasion/adversarial_patch/adversarial_patch.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_pytorch.py
  art/attacks/evasion/over_the_air_flickering/over_the_air_flickering_pytorch.py
  art/estimators/classification/pytorch.py
  art/estimators/object_detection/python_object_detector.py
  art/preprocessing/expectation_over_transformation/image_rotation/pytorch.py
  tests/attacks/inference/membership_inference/test_label_only_boundary_distance.py
  tests/attacks/test_adversarial_patch.py
Labels: enhancement

#1574 fix for rescale not set bug
  art/attacks/evasion/pixel_threshold.py
Labels: bug, improvement

#1513 Add support for Summary Writer in RobustDPatch
  art/attacks/evasion/dpatch_robust.py
Labels: enhancement

#1531 DeepZ Certification
  art/estimators/certification/__init__.py
  art/estimators/certification/deep_z/__init__.py
  art/estimators/certification/deep_z/deep_z.py
  art/estimators/certification/deep_z/pytorch.py
  notebooks/README.md
  notebooks/certification_deepz.ipynb
  run_tests.sh
  tests/estimators/certification/output_results/mini_nets/cifar10_lb_results_0.004.json
  tests/estimators/certification/output_results/mini_nets/cifar10_ub_results_0.004.json
  tests/estimators/certification/output_results/mini_nets/mnist_lb_results_0.05.json
  tests/estimators/certification/output_results/mini_nets/mnist_ub_results_0.05.json
  tests/estimators/certification/test_deepz.py
  tests/utils.py
  utils/data/images/zonotope_picture.png
  utils/resources/models/B_CONV2D_NO_MPOOL_CIFAR10.npy
  utils/resources/models/B_CONV2D_NO_MPOOL_MNIST.npy
  utils/resources/models/B_DENSE_NO_MPOOL_CIFAR10.npy
  utils/resources/models/B_DENSE_NO_MPOOL_MNIST.npy
  utils/resources/models/W_CONV2D_NO_MPOOL_CIFAR10.npy
  utils/resources/models/W_CONV2D_NO_MPOOL_MNIST.npy
  utils/resources/models/W_DENSE_NO_MPOOL_CIFAR10.npy
  utils/resources/models/W_DENSE_NO_MPOOL_MNIST.npy
Labels: enhancement

#1566 Add channel dimension to input in classifier_blackbox_tesseract
  notebooks/classifier_blackbox_tesseract.ipynb
Labels: improvement, notebooks

#1557 Add support for perspective transformation of texture in AdversarialTexturePyTorch
  art/attacks/evasion/adversarial_texture/adversarial_texture_pytorch.py
  tests/attacks/evasion/test_adversarial_texture_pytorch.py
Labels: improvement

#1587 Gradient matching (Witches' Brew) for Tensorflow
  art/attacks/poisoning/__init__.py
  art/attacks/poisoning/gradient_matching_attack.py
  notebooks/README.md
  tests/attacks/poison/test_gradient_matching_attack.py
Labels: enhancement

#1588 Support slices of size 1 in attribute attacks
  art/attacks/inference/attribute_inference/baseline.py
  art/attacks/inference/attribute_inference/black_box.py
  art/attacks/inference/attribute_inference/meminf_based.py
  art/attacks/inference/attribute_inference/true_label_baseline.py
  art/utils.py
  tests/attacks/inference/attribute_inference/test_baseline.py
  tests/attacks/inference/attribute_inference/test_black_box.py
  tests/attacks/inference/attribute_inference/test_meminf_based.py
  tests/attacks/inference/attribute_inference/test_true_label_baseline.py
Labels: improvement

#1586 Add functions for orthogonal projection on L1 balls
  art/utils.py
Labels: enhancement, improvement

#1490 Implement backdoor attacks on DGMs
  art/attacks/attack.py
  art/attacks/poisoning/backdoor_attack_dgm_red.py
  art/attacks/poisoning/backdoor_attack_dgm_trail.py
  art/estimators/gan/__init__.py
  art/estimators/gan/tensorflow_gan.py
  art/estimators/generation/tensorflow.py
  art/utils.py
  conftest.py
  examples/backdoor_attack_dgm_red.py
  examples/backdoor_attack_dgm_trail.py
  notebooks/backdoor_attack_DGM.ipynb
  tests/attacks/poison/test_backdoor_attack_dgm_red.py
  tests/attacks/poison/test_backdoor_attack_dgm_trail.py
  tests/utils.py
Labels: enhancement

#1589 Check scipy version for PixelThreshold attack
  art/attacks/evasion/pixel_threshold.py
  tests/defences/trainer/test_adversarial_trainer_FBF.py
Labels: improvement

#1487 Hidden trigger Backdoor Poisoning Attack Implementation
  art/attacks/poisoning/__init__.py
  art/attacks/poisoning/hidden_trigger_backdoor/__init__.py
  art/attacks/poisoning/hidden_trigger_backdoor/hidden_trigger_backdoor.py
  art/attacks/poisoning/hidden_trigger_backdoor/hidden_trigger_backdoor_keras.py
  art/attacks/poisoning/hidden_trigger_backdoor/hidden_trigger_backdoor_pytorch.py
  art/attacks/poisoning/hidden_trigger_backdoor/loss_meter.py
  art/estimators/certification/randomized_smoothing/pytorch.py
  art/estimators/classification/pytorch.py
  art/estimators/classification/tensorflow.py
  notebooks/README.md
  notebooks/art-for-tensorflow-v2-keras.ipynb
  notebooks/attack_feature_adversaries_pytorch.ipynb
  notebooks/hidden_trigger_backdoor/poisoning_attack_hidden_trigger_keras.ipynb
  notebooks/hidden_trigger_backdoor/poisoning_attack_hidden_trigger_pytorch.ipynb
  notebooks/hidden_trigger_backdoor/poisoning_attack_hidden_trigger_tf.ipynb
  notebooks/poisoning_attack_backdoor_image.ipynb
  notebooks/poisoning_attack_feature_collision.ipynb
  tests/attacks/poison/test_hidden_trigger_backdoor.py
  utils/data/backdoors/htbd.png
Labels: enhancement
