Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2022-06, with the labels that each got.

#1724 bug fix: zero the grads on the patch after each iteration
  art/attacks/evasion/adversarial_texture/adversarial_texture_pytorch.py
Labels: bug, improvement

#1726 bug fix: zero the grads on the patch after each iteration
  art/attacks/evasion/adversarial_texture/adversarial_texture_pytorch.py
Labels: bug, improvement

#1727 Update to ART 1.10.3
  .github/workflows/ci-style-checks.yml
  art/attacks/evasion/adversarial_texture/adversarial_texture_pytorch.py
Labels: release

#1614 Add MIFGSM
  AUTHORS
  art/attacks/evasion/__init__.py
  art/attacks/evasion/fast_gradient.py
  art/attacks/evasion/momentum_iterative_method.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_numpy.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_tensorflow_v2.py
  tests/attacks/evasion/test_momentum_iterative_method.py
Labels: enhancement

#1713 Send nb_classes to check_and_transform_label_format in inference attacks
  art/attacks/inference/attribute_inference/baseline.py
  art/attacks/inference/attribute_inference/black_box.py
  art/attacks/inference/attribute_inference/true_label_baseline.py
  art/attacks/inference/membership_inference/black_box_rule_based.py
  tests/attacks/inference/attribute_inference/test_true_label_baseline.py
Labels: bug, improvement

#1709 MIA worst case score
  art/metrics/privacy/__init__.py
  art/metrics/privacy/worst_case_mia_score.py
  notebooks/attack_membership_inference.ipynb
  tests/metrics/privacy/test_worst_case_mia_score.py
Labels: enhancement

#1742 PyTorchClassifier: delete optimizer before calling set_param()
  art/estimators/classification/pytorch.py
Labels: bug, improvement

#1730 Implement SIGN-OPT: A Query-Efficient Hard-label Black-box Attack
  art/attacks/evasion/__init__.py
  art/attacks/evasion/sign_opt.py
  docs/modules/attacks/evasion.rst
  tests/attacks/evasion/test_sign_opt.py
  tests/attacks/utils.py
Labels: enhancement

#1729 Derandomized smoothing
  art/estimators/certification/__init__.py
  art/estimators/certification/derandomized_smoothing/__init__.py
  art/estimators/certification/derandomized_smoothing/derandomized_smoothing.py
  art/estimators/certification/derandomized_smoothing/pytorch.py
  art/estimators/certification/derandomized_smoothing/tensorflow.py
  art/utils.py
  run_tests.sh
  tests/estimators/certification/test_derandomized_smoothing.py
  utils/resources/models/certification/derandomized/B_CONV2D1_MNIST.npy
  utils/resources/models/certification/derandomized/B_DENSE1_MNIST.npy
  utils/resources/models/certification/derandomized/B_DENSE2_MNIST.npy
  utils/resources/models/certification/derandomized/W_CONV2D1_MNIST.npy
  utils/resources/models/certification/derandomized/W_DENSE1_MNIST.npy
  utils/resources/models/certification/derandomized/W_DENSE2_MNIST.npy
Labels: enhancement

#1758 Update default value for nb_epochs in AdversarialTrainerMadryPGD
  art/defences/trainer/adversarial_trainer_madry_pgd.py
Labels: improvement

#1736 Implement sleeper agent hidden trigger backdoor attack in PyTorch
  art/attacks/poisoning/gradient_matching_attack.py
  art/attacks/poisoning/sleeper_agent_attack.py
  notebooks/README.md
  notebooks/poisoning_attack_sleeper_agent_pytorch.ipynb
  notebooks/trigger_10.png
Labels: enhancement

#1759 Add targeted option to AdversarialPatch and AdversarialPatchNumpy
  art/attacks/evasion/adversarial_patch/adversarial_patch.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_numpy.py
Labels: improvement

#1738 Exclusionary Reclassification
  art/defences/detector/poison/activation_defence.py
  art/estimators/classification/classifier.py
  art/estimators/classification/keras.py
  notebooks/poisoning_defense_activation_clustering.ipynb
  tests/defences/detector/poison/test_activation_defence.py
Labels: enhancement, improvement

#1762 Maintenance updates for ART 1.11.0
  art/attacks/evasion/auto_attack.py
  art/attacks/evasion/auto_projected_gradient_descent.py
  art/attacks/evasion/boundary.py
  art/attacks/evasion/brendel_bethge.py
  art/attacks/evasion/carlini.py
  art/attacks/evasion/decision_tree_attack.py
  art/attacks/evasion/elastic_net.py
  art/attacks/evasion/fast_gradient.py
  art/attacks/evasion/geometric_decision_based_attack.py
  art/attacks/evasion/hop_skip_jump.py
  art/attacks/evasion/over_the_air_flickering/over_the_air_flickering_pytorch.py
  art/attacks/evasion/pixel_threshold.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_numpy.py
  art/attacks/evasion/saliency_map.py
  art/attacks/evasion/shadow_attack.py
  art/attacks/evasion/sign_opt.py
  art/attacks/evasion/square_attack.py
  art/attacks/evasion/universal_perturbation.py
  art/attacks/evasion/wasserstein.py
  art/attacks/evasion/zoo.py
  art/attacks/inference/attribute_inference/black_box.py
  art/attacks/inference/attribute_inference/true_label_baseline.py
  art/attacks/inference/membership_inference/black_box.py
  art/attacks/inference/membership_inference/black_box_rule_based.py
  art/attacks/inference/membership_inference/label_only_boundary_distance.py
  art/attacks/inference/model_inversion/mi_face.py
  art/attacks/poisoning/hidden_trigger_backdoor/hidden_trigger_backdoor_keras.py
  art/attacks/poisoning/hidden_trigger_backdoor/hidden_trigger_backdoor_pytorch.py
  art/attacks/poisoning/sleeper_agent_attack.py
  art/estimators/certification/derandomized_smoothing/pytorch.py
  art/estimators/certification/derandomized_smoothing/tensorflow.py
  art/estimators/certification/randomized_smoothing/pytorch.py
  art/estimators/certification/randomized_smoothing/tensorflow.py
  art/estimators/classification/keras.py
  art/estimators/classification/mxnet.py
  art/estimators/classification/pytorch.py
  art/estimators/classification/tensorflow.py
  art/metrics/privacy/membership_leakage.py
  art/utils.py
  tests/attacks/evasion/test_sign_opt.py
  tests/estimators/object_detection/test_pytorch_yolo.py
  tests/test_utils.py
Labels: improvement
