Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2022-12, with the labels that each got.

#1934 numpy data generators
  art/data_generators.py
  tests/test_data_generators.py
Labels: enhancement

#1955 bug fix for getting best poison indices after all trials
  art/attacks/poisoning/sleeper_agent_attack.py
Labels: improvement

#1927 removed 'from torch.autograd.gradcheck import zero_gradients' from th…
  notebooks/imperceptible_attack_on_tabular_data.ipynb
Labels: improvement, notebooks

#1930 Blackbox regressor support + shadow support for additional models
  art/attacks/inference/membership_inference/shadow_models.py
  art/estimators/classification/classifier.py
  art/estimators/classification/detector_classifier.py
  art/estimators/classification/ensemble.py
  art/estimators/classification/keras.py
  art/estimators/classification/mxnet.py
  art/estimators/classification/tensorflow.py
  art/estimators/classification/xgboost.py
  art/estimators/estimator.py
  art/estimators/keras.py
  art/estimators/regression/__init__.py
  art/estimators/regression/blackbox.py
  art/estimators/regression/regressor.py
  art/utils.py
  run_tests.sh
  tests/estimators/classification/test_xgboost.py
  tests/estimators/regression/test_blackbox.py
Labels: enhancement

#1956 DP-InstaHide Trainer Implementation
  art/defences/trainer/__init__.py
  art/defences/trainer/dp_instahide_trainer.py
  art/estimators/classification/keras.py
  art/estimators/classification/pytorch.py
  art/estimators/classification/tensorflow.py
  notebooks/README.md
  notebooks/poisoning_defense_dp_instahide.ipynb
  tests/defences/trainer/test_dp_instahide_trainer.py
Labels: enhancement

#1951 Adding TFv2 support for Faster-RCNN
  .github/actions/tfv2-faster-rcnn/Dockerfile
  .github/actions/tfv2-faster-rcnn/action.yml
  .github/actions/tfv2-faster-rcnn/run.sh
  .github/workflows/ci-tfv2-faster-rcnn.yml
  art/estimators/object_detection/tensorflow_v2_faster_rcnn.py
  notebooks/README.md
  notebooks/adversarial_patch/attack_adversarial_patch_faster_rcnn.ipynb
  tests/estimators/object_detection/test_tensorflow_v2_faster_rcnn.py
Labels: enhancement

#1962 Fix incorrect shape issue when loading raw CIFAR-10 data
  art/utils.py
Labels: improvement
