Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2022-05, with the labels that each got.

#1653 Fix Label Only Notebook
  notebooks/README.md
  notebooks/label_only_membership_inference.ipynb
Labels: improvement, notebooks

#1648 Zoo documentation
  art/attacks/evasion/zoo.py
Labels: improvement

#1677 Imperceptible asr bug detach
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
Labels: bug, improvement

#1680 Mp3Compression defense bug fix - handle case when input is 2D but not an object array
  art/defences/preprocessor/mp3_compression.py
Labels: bug, improvement

#1678 Randomised smoothing fix
  art/estimators/certification/randomized_smoothing/numpy.py
  art/estimators/certification/randomized_smoothing/pytorch.py
  art/estimators/certification/randomized_smoothing/randomized_smoothing.py
  art/estimators/certification/randomized_smoothing/tensorflow.py
Labels: bug, improvement

#1684 fix: fixed np.sum in art/defences/postprocessor/gaussian_noise.py
  art/defences/postprocessor/gaussian_noise.py
Labels: bug, improvement

#1580 PyTorchClassifier: use a new optimizer for the cloned classifier
  art/estimators/classification/pytorch.py
Labels: bug, improvement

#1699 Add argument batch_size to CarliniLInfMethod
  art/attacks/evasion/carlini.py
Labels: improvement

#1698 Support numpy arrays in logger of clean_label_backdoor_attack
  art/attacks/poisoning/clean_label_backdoor_attack.py
Labels: bug, improvement

#1693 Update RobustDPatch for channels first images
  art/attacks/evasion/dpatch_robust.py
  art/estimators/object_detection/pytorch_faster_rcnn.py
  art/estimators/object_detection/pytorch_object_detector.py
  tests/attacks/evasion/test_dpatch_robust.py
Labels: bug, improvement

#1655 Update DGM poisoning attacks for TensorFlow dependency
  art/attacks/poisoning/__init__.py
  art/attacks/poisoning/backdoor_attack_dgm/__init__.py
  art/attacks/poisoning/backdoor_attack_dgm/backdoor_attack_dgm_red.py
  art/attacks/poisoning/backdoor_attack_dgm/backdoor_attack_dgm_trail.py
  art/estimators/gan/__init__.py
  art/estimators/gan/tensorflow.py
  art/estimators/generation/__init__.py
  art/estimators/generation/tensorflow.py
  art/utils.py
  docs/modules/attacks/poisoning.rst
  docs/modules/estimators/generation.rst
  examples/backdoor_attack_dgm_red.py
  examples/backdoor_attack_dgm_trail.py
  notebooks/backdoor_attack_DGM.ipynb
  tests/attacks/poison/test_backdoor_attack_dgm_red.py
  tests/attacks/poison/test_backdoor_attack_dgm_trail.py
  tests/utils.py
Labels: bug, improvement

#1702 Add support for framework-specific preprocessing of object arrays
  .github/actions/deepspeech-v2/Dockerfile
  .github/actions/deepspeech-v3/Dockerfile
  .github/workflows/ci-deepspeech-v2.yml
  .github/workflows/ci-deepspeech-v3.yml
  art/defences/preprocessor/mp3_compression_pytorch.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
  tests/attacks/evasion/test_imperceptible_asr_pytorch.json
  tests/attacks/evasion/test_imperceptible_asr_pytorch.py
  tests/estimators/speech_recognition/test_pytorch_deep_speech.json
  tests/estimators/speech_recognition/test_pytorch_deep_speech.py
Labels: improvement

#1710 Update to ART 1.10.2
  .github/actions/deepspeech-v2/Dockerfile
  .github/actions/deepspeech-v3/Dockerfile
  .github/workflows/ci-deepspeech-v2.yml
  .github/workflows/ci-deepspeech-v3.yml
  art/attacks/evasion/carlini.py
  art/attacks/evasion/dpatch_robust.py
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
  art/attacks/poisoning/__init__.py
  art/attacks/poisoning/backdoor_attack_dgm/__init__.py
  art/attacks/poisoning/backdoor_attack_dgm/backdoor_attack_dgm_red.py
  art/attacks/poisoning/backdoor_attack_dgm/backdoor_attack_dgm_trail.py
  art/attacks/poisoning/clean_label_backdoor_attack.py
  art/defences/postprocessor/gaussian_noise.py
  art/defences/preprocessor/mp3_compression.py
  art/defences/preprocessor/mp3_compression_pytorch.py
  art/estimators/certification/randomized_smoothing/numpy.py
  art/estimators/certification/randomized_smoothing/pytorch.py
  art/estimators/certification/randomized_smoothing/randomized_smoothing.py
  art/estimators/certification/randomized_smoothing/tensorflow.py
  art/estimators/classification/pytorch.py
  art/estimators/gan/__init__.py
  art/estimators/gan/tensorflow.py
  art/estimators/generation/__init__.py
  art/estimators/generation/tensorflow.py
  art/estimators/object_detection/__init__.py
  art/estimators/object_detection/pytorch_faster_rcnn.py
  art/estimators/object_detection/pytorch_object_detector.py
  art/estimators/speech_recognition/pytorch_deep_speech.py
  art/utils.py
  docs/modules/attacks/poisoning.rst
  docs/modules/estimators/generation.rst
  examples/backdoor_attack_dgm_red.py
  examples/backdoor_attack_dgm_trail.py
  notebooks/backdoor_attack_DGM.ipynb
  tests/attacks/evasion/test_dpatch_robust.py
  tests/attacks/evasion/test_imperceptible_asr_pytorch.json
  tests/attacks/evasion/test_imperceptible_asr_pytorch.py
  tests/attacks/poison/test_backdoor_attack_dgm_red.py
  tests/attacks/poison/test_backdoor_attack_dgm_trail.py
  tests/estimators/object_detection/test_pytorch_object_detector.py
  tests/estimators/speech_recognition/test_pytorch_deep_speech.json
  tests/estimators/speech_recognition/test_pytorch_deep_speech.py
  tests/utils.py
Labels: release
