Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2022-01, with the labels that each got.

#1467 Fix import of matplotlib in laser attack utils
  art/attacks/evasion/laser_attack/utils.py
Labels: bug, improvement

#1466 Add support in KerasClassifier.compute_loss for TF 1.15 as backend
  art/estimators/classification/keras.py
Labels: improvement

#1460 Fix bug when loading nursery data
  art/utils.py
  tests/test_utils.py
Labels: bug, improvement

#1471 Replace x with x_preprocessed in PyTorchClassifier.get_activations
  art/estimators/classification/pytorch.py
Labels: bug, improvement

#1476 Update to ART 1.9.1
  art/__init__.py
  art/attacks/evasion/laser_attack/utils.py
  art/defences/preprocessor/video_compression.py
  art/defences/preprocessor/video_compression_pytorch.py
  art/estimators/classification/keras.py
  art/estimators/classification/pytorch.py
  art/estimators/object_tracking/pytorch_goturn.py
  art/utils.py
  docs/conf.py
  tests/test_utils.py
Labels: release
