Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2022-08, with the labels that each got.

#1817 Fixed runtime error
  examples/get_started_tensorflow.py
Labels: improvement

#1779 Add adversarial_accuracy as a metric
  art/metrics/metrics.py
  tests/metrics/test_metrics.py
Labels: enhancement

#1824 Remove call to detach() on a numpy array
  art/estimators/regression/pytorch.py
Labels: bug, improvement

#1825 PDTP fixes
  art/metrics/privacy/membership_leakage.py
  art/utils.py
  tests/metrics/privacy/test_membership_leakage.py
Labels: bug, improvement
