Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2022-09, with the labels that each got.

#1833 Fix learning rate decay in ElasticNet attack
  art/attacks/evasion/elastic_net.py
  tests/attacks/test_elastic_net.py
Labels: bug, improvement

#1845 Update to ART 1.11.1
  art/attacks/evasion/adversarial_patch/adversarial_patch.py
  art/attacks/evasion/adversarial_patch/adversarial_patch_pytorch.py
  art/attacks/evasion/elastic_net.py
  art/estimators/classification/pytorch.py
  art/estimators/regression/pytorch.py
  art/metrics/privacy/membership_leakage.py
  art/utils.py
  tests/attacks/test_elastic_net.py
  tests/metrics/privacy/test_membership_leakage.py
  tests/test_utils.py
Labels: release

#1778 Shadow models and predictions for membership attack
  art/attacks/inference/membership_inference/black_box.py
  art/attacks/inference/membership_inference/shadow_models.py
  art/estimators/estimator.py
  art/estimators/regression/keras.py
  art/estimators/regression/pytorch.py
  art/estimators/regression/scikitlearn.py
  tests/attacks/inference/membership_inference/test_black_box.py
  tests/attacks/inference/membership_inference/test_shadow_models.py
Labels: enhancement

#1828 Implement GRAPHITE attack, fixed
  AUTHORS
  art/attacks/evasion/__init__.py
  art/attacks/evasion/graphite/__init__.py
  art/attacks/evasion/graphite/graphite_blackbox.py
  art/attacks/evasion/graphite/graphite_whitebox_pytorch.py
  art/attacks/evasion/graphite/utils.py
  notebooks/attack_graphite_blackbox.ipynb
  notebooks/attack_graphite_whitebox.ipynb
  run_tests.sh
  tests/attacks/test_graphite.py
Labels: enhancement

#1804 Create sample_from_sphere_or_ball
  sample_from_sphere_or_ball
Labels: enhancement, improvement

#1805 Update utils.py
  art/utils.py
Labels: improvement

#1841 Certified training
  art/defences/trainer/__init__.py
  art/defences/trainer/certified_adversarial_trainer_pytorch.py
  art/estimators/certification/deep_z/deep_z.py
  art/estimators/certification/deep_z/pytorch.py
  art/utils.py
  docs/modules/defences/trainer.rst
  notebooks/README.md
  notebooks/certified_adversarial_training.ipynb
  tests/defences/trainer/test_certified_adversarial_trainer.py
  tests/estimators/certification/test_deepz.py
  utils/data/images/cert_training.png
Labels: enhancement

#1769 Implement Sleeper Agent Poisoning Attack in TensorFlow
  art/attacks/poisoning/gradient_matching_attack.py
  art/attacks/poisoning/sleeper_agent_attack.py
  notebooks/poisoning_attack_sleeper_agent.ipynb
  notebooks/poisoning_attack_sleeper_agent_pytorch.ipynb
  tests/attacks/poison/test_sleeper_agent_attack.py
Labels: enhancement

#1848 Move new random sampling method to art.utils
  art/utils.py
  tests/test_utils.py
Labels: enhancement, improvement

#1855 Update to ART 1.12.0
  AUTHORS
  art/attacks/evasion/__init__.py
  art/attacks/evasion/dpatch.py
  art/attacks/evasion/graphite/__init__.py
  art/attacks/evasion/graphite/graphite_blackbox.py
  art/attacks/evasion/graphite/graphite_whitebox_pytorch.py
  art/attacks/evasion/graphite/utils.py
  art/attacks/inference/membership_inference/black_box.py
  art/attacks/inference/membership_inference/shadow_models.py
  art/attacks/poisoning/gradient_matching_attack.py
  art/attacks/poisoning/sleeper_agent_attack.py
  art/defences/trainer/__init__.py
  art/defences/trainer/certified_adversarial_trainer_pytorch.py
  art/estimators/certification/deep_z/deep_z.py
  art/estimators/certification/deep_z/pytorch.py
  art/estimators/estimator.py
  art/estimators/regression/keras.py
  art/estimators/regression/pytorch.py
  art/estimators/regression/scikitlearn.py
  art/metrics/metrics.py
  art/utils.py
  docs/modules/defences/trainer.rst
  notebooks/README.md
  notebooks/attack_graphite_blackbox.ipynb
  notebooks/attack_graphite_whitebox.ipynb
  notebooks/certified_adversarial_training.ipynb
  notebooks/poisoning_attack_sleeper_agent.ipynb
  notebooks/poisoning_attack_sleeper_agent_pytorch.ipynb
  run_tests.sh
  tests/attacks/evasion/test_dpatch.py
  tests/attacks/inference/membership_inference/test_black_box.py
  tests/attacks/inference/membership_inference/test_shadow_models.py
  tests/attacks/poison/test_sleeper_agent_attack.py
  tests/attacks/test_graphite.py
  tests/defences/trainer/test_certified_adversarial_trainer.py
  tests/estimators/certification/test_deepz.py
  tests/metrics/test_metrics.py
  tests/test_utils.py
  utils/data/images/cert_training.png
Labels: release

#1860 Fix batch-norm layers in PyTorchYolo._get_losses
  art/estimators/object_detection/pytorch_yolo.py
Labels: bug, improvement

#1861 Update to ART 1.12.1
  art/estimators/object_detection/pytorch_yolo.py
Labels: release
