Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2022-02, with the labels that each got.

#1488 Fix fitting warning when using attack_model_type 'rf' or 'gb'
  art/attacks/inference/membership_inference/black_box.py
Labels: bug, improvement

#1512 Fix scalar names for indicators 2 and 3 for aggregated losses
  art/summary_writer.py
Labels: bug, improvement

#1537 Fix ScikitlearnRegressor fit method
  art/estimators/regression/scikitlearn.py
  tests/attacks/test_threshold_attack.py
  tests/estimators/classification/test_scikitlearn.py
  tests/estimators/regression/test_scikitlearn.py
  tests/utils.py
Labels: bug, improvement

#1556 Fix several minor typos in some notebooks and an example file
  examples/inverse_gan_author_utils.py
  notebooks/adaptive_defence_evaluations/evaluation_12_EMPIR.ipynb
  notebooks/adversarial_training_mnist.ipynb
  notebooks/attack_database_reconstruction.ipynb
  notebooks/attack_defence_imagenet.ipynb
  notebooks/attack_laser.ipynb
  notebooks/attack_membership_inference.ipynb
  notebooks/attack_membership_inference_shadow_models.ipynb
  notebooks/classifier_blackbox_lookup_table.ipynb
  notebooks/classifier_gpy_gaussian_process.ipynb
  notebooks/classifier_scikitlearn_AdaBoostClassifier.ipynb
  notebooks/classifier_scikitlearn_RandomForestClassifier.ipynb
  notebooks/classifier_scikitlearn_SVC_LinearSVC.ipynb
  notebooks/classifier_scikitlearn_pipeline_pca_cv_svc.ipynb
  notebooks/expectation_over_transformation_classification_rotation.ipynb
  notebooks/imperceptible_attack_on_tabular_data.ipynb
  notebooks/label_only_membership_inference.ipynb
  notebooks/poisoning_attack_svm.ipynb
  notebooks/poisoning_defense_deep_partition_aggregation.ipynb
  notebooks/provenance_defence.ipynb
Labels: improvement

#1550 Fixes torchaudio.functional.magphase use for Deep Speech 2 version 3
  .github/workflows/ci-deepspeech-v3.yml
  art/estimators/speech_recognition/pytorch_deep_speech.py
Labels: bug, improvement

#1516 Add EoT center crop and rotation for object detection in PyTorch
  art/attacks/evasion/dpatch_robust.py
  art/defences/preprocessor/preprocessor.py
  art/preprocessing/expectation_over_transformation/__init__.py
  art/preprocessing/expectation_over_transformation/image_center_crop/__init__.py
  art/preprocessing/expectation_over_transformation/image_center_crop/pytorch.py
  art/preprocessing/expectation_over_transformation/image_rotation/pytorch.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/brightness/pytorch.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/contrast/pytorch.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/contrast/tensorflow.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/gaussian_noise/pytorch.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/shot_noise/pytorch.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/zoom_blur/pytorch.py
  art/preprocessing/expectation_over_transformation/natural_corruptions/zoom_blur/tensorflow.py
  art/preprocessing/expectation_over_transformation/pytorch.py
  art/preprocessing/expectation_over_transformation/tensorflow.py
  tests/defences/trainer/test_adversarial_trainer_FBF.py
  tests/preprocessing/expectation_over_transformation/test_image_rotation.py
Labels: enhancement
