Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2022-04, with the labels that each got.

#1607 Check if mask is None in AdversarialPatchPyTorch.apply_patch
  art/attacks/evasion/adversarial_patch/adversarial_patch_pytorch.py
Labels: bug, improvement

#1598 Correct handling of labels for regression models in attribute attacks
  art/attacks/inference/attribute_inference/black_box.py
  art/attacks/inference/attribute_inference/true_label_baseline.py
  tests/attacks/inference/attribute_inference/test_black_box.py
  tests/attacks/inference/attribute_inference/test_true_label_baseline.py
Labels: bug, improvement

#1624 Gradient matching unknown input shape support
  art/attacks/poisoning/gradient_matching_attack.py
Labels: improvement

#1633 Add support for multi-channel images in PyTorchObjectDetector
  art/estimators/object_detection/python_object_detector.py
  art/estimators/object_detection/pytorch_faster_rcnn.py
Labels: improvement

#1612 Add nb_epochs and batch_size to AdversarialTrainerMadryPGD.fit
  .github/workflows/ci-style-checks.yml
  art/defences/trainer/adversarial_trainer_madry_pgd.py
Labels: improvement

#1645 Update to ART 1.10.1
  .github/workflows/ci-style-checks.yml
  art/attacks/evasion/adversarial_patch/adversarial_patch_pytorch.py
  art/attacks/inference/attribute_inference/black_box.py
  art/attacks/inference/attribute_inference/true_label_baseline.py
  art/attacks/poisoning/gradient_matching_attack.py
  art/defences/trainer/adversarial_trainer_madry_pgd.py
  art/estimators/object_detection/python_object_detector.py
  art/estimators/object_detection/pytorch_faster_rcnn.py
  tests/attacks/inference/attribute_inference/test_black_box.py
  tests/attacks/inference/attribute_inference/test_true_label_baseline.py
Labels: release
