Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2022-07, with the labels that each got.

#1766 Fix attribute inference notebook
  art/attacks/inference/membership_inference/shadow_models.py
  notebooks/attack_attribute_inference.ipynb
Labels: notebooks

#1768 Fix untargeted attack in Adversarial Patch
  art/attacks/evasion/adversarial_patch/adversarial_patch.py
Labels: bug, improvement

#1783 Fix typo in nbviewer URL
  notebooks/README.md
Labels: notebooks

#1780 DPatch: def parameter updated to accept true labels
  art/attacks/evasion/dpatch.py
  tests/attacks/evasion/test_dpatch.py
Labels: improvement

#1785 Fix exception in pytorch classifier predict method
  art/estimators/classification/pytorch.py
Labels: bug, improvement
