Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2022-11, with the labels that each got.

#1870 Update utils.py
  art/utils.py
Labels: improvement

#1892 Bug fix sleeper agent
  art/attacks/poisoning/sleeper_agent_attack.py
Labels: improvement

#1890 Small clarification fix for verification alg
  art/metrics/verification_decisions_trees.py
Labels: improvement

#1854 Adding YOLO examples to ART
  art/estimators/object_detection/pytorch_yolo.py
  examples/get_started_yolo.py
  notebooks/README.md
  notebooks/adversarial_patch/attack_adversarial_patch_pytorch_yolo.ipynb
Labels: improvement

#1850 Implement Cutout in Numpy, PyTorch, and TensorFlow
  art/defences/preprocessor/__init__.py
  art/defences/preprocessor/cutout/__init__.py
  art/defences/preprocessor/cutout/cutout.py
  art/defences/preprocessor/cutout/cutout_pytorch.py
  art/defences/preprocessor/cutout/cutout_tensorflow.py
  tests/defences/preprocessor/cutout/test_cutout.py
  tests/defences/preprocessor/cutout/test_cutout_pytorch.py
  tests/defences/preprocessor/cutout/test_cutout_tensorflow.py
Labels: enhancement

#1897 Remove check from BoundaryAttack to enable binary classification
  art/attacks/evasion/boundary.py
Labels: improvement

#1883 Add drop_last option to method fit of PyTorchClassifier
  art/estimators/certification/derandomized_smoothing/pytorch.py
  art/estimators/certification/randomized_smoothing/pytorch.py
  art/estimators/classification/pytorch.py
Labels: improvement

#1912 Update to ART 1.12.2
  art/attacks/evasion/__init__.py
  art/attacks/evasion/boundary.py
  art/attacks/poisoning/sleeper_agent_attack.py
  art/estimators/certification/derandomized_smoothing/pytorch.py
  art/estimators/certification/randomized_smoothing/pytorch.py
  art/estimators/classification/pytorch.py
  art/metrics/verification_decisions_trees.py
  art/utils.py
  setup.py
Labels: release

#1885 Implement Mixup in Numpy, PyTorch, and TensorFlow
  art/defences/preprocessor/__init__.py
  art/defences/preprocessor/mixup/__init__.py
  art/defences/preprocessor/mixup/mixup.py
  art/defences/preprocessor/mixup/mixup_pytorch.py
  art/defences/preprocessor/mixup/mixup_tensorflow.py
  tests/defences/preprocessor/mixup/test_mixup.py
  tests/defences/preprocessor/mixup/test_mixup_pytorch.py
  tests/defences/preprocessor/mixup/test_mixup_tensorflow.py
Labels: enhancement

#1910 Implement CutMix in Numpy, PyTorch, and TensorFlow
  art/defences/preprocessor/__init__.py
  art/defences/preprocessor/cutmix/__init__.py
  art/defences/preprocessor/cutmix/cutmix.py
  art/defences/preprocessor/cutmix/cutmix_pytorch.py
  art/defences/preprocessor/cutmix/cutmix_tensorflow.py
  tests/defences/preprocessor/cutmix/test_cutmix.py
  tests/defences/preprocessor/cutmix/test_cutmix_pytorch.py
  tests/defences/preprocessor/cutmix/test_cutmix_tensorflow.py
Labels: enhancement
