Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2023-05, with the labels that each got.

#2129 Remove incorrectly duplicated queries in SignOPT attack
  art/attacks/evasion/sign_opt.py
  requirements_test.txt
Labels: improvement

#2143 Fix Image Poisoning Perturbations Trigger Placement Bug
  art/attacks/poisoning/perturbations/image_perturbations.py
Labels: bug, improvement

#2135 Fix Tensor Device Inconsistencies in PGD
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
Labels: bug, improvement

#2137 Update model_inversion_attacks_mnist.ipynb
  notebooks/model_inversion_attacks_mnist.ipynb
Labels: notebooks

#2131 TRADES adversarial training protocol
  art/defences/trainer/__init__.py
  art/defences/trainer/adversarial_trainer_trades.py
  art/defences/trainer/adversarial_trainer_trades_pytorch.py
  examples/adversarial_training_trades.py
  tests/defences/trainer/test_adversarial_trainer_trades_pytorch.py
Labels: enhancement

#2124 Implement Default Training Loop for `TensorFlowV2Classifier`
  art/attacks/evasion/auto_conjugate_gradient.py
  art/attacks/evasion/auto_projected_gradient_descent.py
  art/attacks/evasion/brendel_bethge.py
  art/estimators/certification/derandomized_smoothing/tensorflow.py
  art/estimators/certification/randomized_smoothing/tensorflow.py
  art/estimators/classification/tensorflow.py
  examples/get_started_tensorflow_v2.py
  notebooks/attack_feature_adversaries_tensorflow_v2.ipynb
  notebooks/output_randomized_smoothing_mnist.ipynb
  notebooks/poisoning_attack_backdoor_audio.ipynb
  notebooks/poisoning_attack_sleeper_agent.ipynb
  tests/defences/detector/evasion/test_binary_activation_detector.py
  tests/defences/detector/evasion/test_binary_input_detector.py
  tests/defences/trainer/test_dp_instahide_trainer.py
  tests/estimators/certification/test_derandomized_smoothing.py
  tests/estimators/certification/test_randomized_smoothing.py
  tests/estimators/classification/test_deep_partition_ensemble.py
  tests/estimators/classification/test_deeplearning_common.json
  tests/utils.py
Labels: improvement
