Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2023-12, with the labels that each got.

#2300 Huggingface model wrapper update
  art/estimators/classification/hugging_face.py
  notebooks/huggingface_notebook.ipynb
Labels: bug, improvement

#2327 Fix `ActivationDefense` and `SpectralSignatures` expected flattened bug
  art/defences/detector/poison/activation_defence.py
  art/defences/detector/poison/spectral_signature_defense.py
Labels: bug, improvement

#2338 Hugging Face Notebook Improvements
  notebooks/huggingface_notebook.ipynb
Labels: improvement

#2373 Update to ART 1.17.0
  art/attacks/evasion/__init__.py
  art/attacks/evasion/composite_adversarial_attack.py
  art/attacks/extraction/knockoff_nets.py
  art/attacks/inference/membership_inference/black_box.py
  art/attacks/poisoning/sleeper_agent_attack.py
  art/defences/detector/poison/activation_defence.py
  art/defences/detector/poison/spectral_signature_defense.py
  art/defences/trainer/__init__.py
  art/defences/trainer/adversarial_trainer.py
  art/defences/trainer/adversarial_trainer_oaat.py
  art/defences/trainer/adversarial_trainer_oaat_pytorch.py
  art/defences/trainer/dp_instahide_trainer.py
  art/estimators/certification/derandomized_smoothing/pytorch.py
  art/estimators/certification/derandomized_smoothing/tensorflow.py
  art/estimators/certification/randomized_smoothing/macer/pytorch.py
  art/estimators/certification/randomized_smoothing/macer/tensorflow.py
  art/estimators/certification/randomized_smoothing/pytorch.py
  art/estimators/certification/randomized_smoothing/randomized_smoothing.py
  art/estimators/certification/randomized_smoothing/smooth_adv/pytorch.py
  art/estimators/certification/randomized_smoothing/smooth_adv/tensorflow.py
  art/estimators/certification/randomized_smoothing/smooth_mix/pytorch.py
  art/estimators/certification/randomized_smoothing/tensorflow.py
  art/estimators/classification/hugging_face.py
  art/estimators/classification/keras.py
  art/estimators/classification/pytorch.py
  art/estimators/classification/tensorflow.py
  examples/adversarial_training_oaat.py
  notebooks/README.md
  notebooks/composite-adversarial-attack.ipynb
  notebooks/huggingface_notebook.ipynb
  tests/attacks/evasion/test_composite_adversarial_attack.py
  tests/attacks/inference/attribute_inference/test_true_label_baseline.py
  tests/attacks/inference/membership_inference/test_black_box.py
  tests/defences/trainer/test_adversarial_trainer_oaat_pytorch.py
  tests/estimators/classification/test_deeplearning_common.py
Labels: release
