Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2023-04, with the labels that each got.

#2089 Update Audio Poisoning Notebook
  notebooks/poisoning_attack_backdoor_audio.ipynb
Labels: notebooks

#2099 Remove deleted codecov package as dependency
  Dockerfile
  requirements_test.txt
  setup.py
Labels: improvement, tests

#2093 Update __init__.py to import adversarial_accuracy
  art/metrics/__init__.py
Labels: bug, improvement

#2091 Fix `PyTorchYolo` Incorrect Inputs and Unify Input Processing
  art/estimators/object_detection/pytorch_yolo.py
  docs/modules/estimators/object_detection.rst
  tests/estimators/object_detection/test_pytorch_yolo.py
Labels: bug, improvement

#2112 IBP Loss Weighting
  art/defences/trainer/ibp_certified_trainer_pytorch.py
Labels: bug, improvement

#2117 Fix bugs in AutoProjectedGradientDescent
  art/attacks/evasion/auto_projected_gradient_descent.py
  tests/attacks/evasion/test_auto_attack.py
  tests/attacks/evasion/test_shadow_attack.py
Labels: bug, improvement
