Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2023-02, with the labels that each got.

#1993 Refactor Evasion Detectors
  art/defences/detector/evasion/__init__.py
  art/defences/detector/evasion/binary_activation_detector.py
  art/defences/detector/evasion/binary_input_detector.py
  art/defences/detector/evasion/detector.py
  art/defences/detector/evasion/evasion_detector.py
  art/defences/detector/evasion/subsetscanning/__init__.py
  art/defences/detector/evasion/subsetscanning/detector.py
  art/defences/detector/evasion/subsetscanning/scoring_functions.py
  docs/modules/defences/detector_evasion.rst
  docs/modules/defences/detector_evasion_subsetscanning.rst
  notebooks/detection_adversarial_samples_cifar10.ipynb
  run_tests.sh
  tests/defences/detector/evasion/subsetscanning/__init__.py
  tests/defences/detector/evasion/subsetscanning/test_detector.py
  tests/defences/detector/evasion/test_binary_activation_detector.py
  tests/defences/detector/evasion/test_binary_input_detector.py
  tests/defences/detector/evasion/test_detector.py
  tests/defences/detector/evasion/test_subsetscanning_detector.py
Labels: improvement

#2021 Add missing transfer to device in FeatureAdversariesPyTorch
  art/attacks/evasion/feature_adversaries/feature_adversaries_pytorch.py
Labels: bug, improvement

#2022 Add conversion to float for comparison on GPU/CUDA
  art/estimators/classification/pytorch.py
Labels: bug, improvement

#2025 Cast nb_classes to integer in check_and_transform_label_format
  art/utils.py
Labels: improvement

#2033 Update to ART 1.13.1
  art/attacks/evasion/feature_adversaries/feature_adversaries_pytorch.py
  art/attacks/evasion/pixel_threshold.py
  art/attacks/poisoning/perturbations/audio_perturbations.py
  art/defences/preprocessor/cutmix/cutmix.py
  art/defences/preprocessor/cutmix/cutmix_pytorch.py
  art/defences/preprocessor/cutmix/cutmix_tensorflow.py
  art/defences/preprocessor/cutout/cutout.py
  art/defences/preprocessor/cutout/cutout_pytorch.py
  art/defences/preprocessor/cutout/cutout_tensorflow.py
  art/defences/preprocessor/mixup/mixup.py
  art/defences/preprocessor/mixup/mixup_pytorch.py
  art/defences/preprocessor/mixup/mixup_tensorflow.py
  art/defences/trainer/dp_instahide_trainer.py
  art/estimators/classification/pytorch.py
  art/estimators/object_detection/__init__.py
  art/metrics/__init__.py
  art/metrics/privacy/__init__.py
  art/metrics/privacy/membership_leakage.py
  art/utils.py
  tests/attacks/poison/test_audio_perturbations.py
  tests/attacks/test_pixel_attack.py
  tests/defences/trainer/test_dp_instahide_trainer.py
  tests/metrics/privacy/test_membership_leakage.py
Labels: release
