Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2023-09, with the labels that each got.

#2263 Remove in-place operations
  art/estimators/object_detection/pytorch_object_detector.py
  art/estimators/object_detection/pytorch_yolo.py
Labels: bug, improvement

#2259 Refactor unittests for Adversarial Trainer Madry PGD
  run_tests.sh
  tests/defences/test_adversarial_trainer_madry_pgd.py
  tests/defences/trainer/test_adversarial_trainer_madry_pgd.py
Labels: improvement

#2266 Fixing README download badges
  README-cn.md
  README.md
Labels: improvement, documentation

#2224 adding adversarial weight perturbation protocol
  art/defences/trainer/__init__.py
  art/defences/trainer/adversarial_trainer_awp.py
  art/defences/trainer/adversarial_trainer_awp_pytorch.py
  examples/adversarial_training_awp.py
  tests/defences/trainer/test_adversarial_trainer_awp_pytorch.py
Labels: enhancement

#2246 ObjectSeeker Defense Implementation
  .github/actions/yolo/run.sh
  .github/workflows/ci-pytorch-object-detectors.yml
  art/estimators/certification/__init__.py
  art/estimators/certification/object_seeker/__init__.py
  art/estimators/certification/object_seeker/object_seeker.py
  art/estimators/certification/object_seeker/pytorch.py
  art/utils.py
  tests/estimators/object_detection/conftest.py
  tests/estimators/object_detection/test_object_seeker_faster_rcnn.py
  tests/estimators/object_detection/test_object_seeker_yolo.py
  tests/estimators/object_detection/test_pytorch_faster_rcnn.py
  tests/estimators/object_detection/test_pytorch_object_detector.py
  tests/estimators/object_detection/test_pytorch_yolo.py
Labels: enhancement

#2265 Update `channels_first` parameter and docstring for PyTorch Object Detectors
  art/estimators/object_detection/pytorch_faster_rcnn.py
  art/estimators/object_detection/pytorch_object_detector.py
  art/estimators/object_detection/pytorch_yolo.py
Labels: bug, improvement

#2274 Printable representation of Attack objects [JATIC-I2-IBM]
  art/attacks/attack.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_numpy.py
  tests/attacks/test_attack.py
Labels: enhancement

#2280 Update to ART 1.15.2
  art/estimators/object_detection/pytorch_faster_rcnn.py
  art/estimators/object_detection/pytorch_object_detector.py
  art/estimators/object_detection/pytorch_yolo.py
Labels: release

#2258 Parallelization support in AutoAttack [JATIC-I2-IBM]
  art/attacks/attack.py
  art/attacks/evasion/auto_attack.py
  art/defences/trainer/adversarial_trainer.py
  art/estimators/classification/pytorch.py
  art/metrics/metrics.py
  notebooks/attack_parallel_auto_attack.ipynb
  requirements_test.txt
  setup.py
  tests/attacks/evasion/test_auto_attack.py
  tests/attacks/test_targeted_universal_perturbation.py
Labels: enhancement

#2276 Fix unsupported operand type(s) for / error in AdversarialPatch in Tensorflow
  art/attacks/evasion/adversarial_patch/adversarial_patch_tensorflow.py
Labels: bug, improvement

#2257 AutoAttack skips attacks not supporting targeted mode [JATIC-I2-IBM]
  tests/attacks/evasion/test_auto_attack.py
Labels: bug, improvement

#2253 Improve attack model types in inference attacks
  art/attacks/inference/attribute_inference/baseline.py
  art/attacks/inference/attribute_inference/black_box.py
  art/attacks/inference/attribute_inference/true_label_baseline.py
  art/attacks/inference/membership_inference/black_box.py
  tests/attacks/inference/attribute_inference/test_baseline.py
  tests/attacks/inference/attribute_inference/test_black_box.py
  tests/attacks/inference/attribute_inference/test_true_label_baseline.py
  tests/attacks/inference/membership_inference/test_black_box.py
Labels: improvement

#2171 Implement smoothed Vision Transformer as defense against patch evasion attacks
  .github/workflows/ci-lingvo.yml
  art/estimators/certification/__init__.py
  art/estimators/certification/derandomized_smoothing/__init__.py
  art/estimators/certification/derandomized_smoothing/ablators/__init__.py
  art/estimators/certification/derandomized_smoothing/ablators/ablate.py
  art/estimators/certification/derandomized_smoothing/ablators/pytorch.py
  art/estimators/certification/derandomized_smoothing/ablators/tensorflow.py
  art/estimators/certification/derandomized_smoothing/derandomized.py
  art/estimators/certification/derandomized_smoothing/pytorch.py
  art/estimators/certification/derandomized_smoothing/tensorflow.py
  art/estimators/certification/derandomized_smoothing/vision_transformers/__init__.py
  art/estimators/certification/derandomized_smoothing/vision_transformers/pytorch.py
  notebooks/README.md
  notebooks/smoothed_vision_transformers.ipynb
  requirements_test.txt
  setup.py
  tests/estimators/certification/test_derandomized_smoothing.py
  tests/estimators/certification/test_vision_transformers.py
  utils/resources/models/certification/smooth_vit/cumulative_predictions.npy
  utils/resources/models/certification/smooth_vit/head_bias.npy
  utils/resources/models/certification/smooth_vit/head_weight.npy
  utils/resources/models/certification/smooth_vit/madry_preds_block.pt
  utils/resources/models/certification/smooth_vit/madry_preds_column.pt
Labels: enhancement

#2245 Implement estimator for Hugging Face models
  .github/workflows/ci-huggingface.yml
  art/attacks/poisoning/hidden_trigger_backdoor/hidden_trigger_backdoor_pytorch.py
  art/attacks/poisoning/perturbations/image_perturbations.py
  art/estimators/classification/__init__.py
  art/estimators/classification/hugging_face.py
  conftest.py
  notebooks/huggingface_notebook.ipynb
  tests/attacks/evasion/feature_adversaries/test_feature_adversaries_tensorflow.py
  tests/attacks/evasion/test_dpatch_robust.py
  tests/attacks/inference/membership_inference/test_black_box.py
  tests/attacks/poison/test_bullseye_polytope_attack.py
  tests/attacks/poison/test_clean_label_backdoor_attack.py
  tests/attacks/poison/test_hidden_trigger_backdoor.py
  tests/defences/trainer/test_adversarial_trainer_FBF.py
  tests/defences/trainer/test_adversarial_trainer_trades_pytorch.py
  tests/defences/trainer/test_certified_adversarial_trainer.py
  tests/defences/trainer/test_dp_instahide_trainer.py
  tests/estimators/classification/test_deeplearning_common.json
  tests/estimators/classification/test_deeplearning_common.py
  tests/utils.py
Labels: enhancement

#2289 AutoAttack metadata describing best attacks [JATIC-I2-IBM]
  art/attacks/evasion/auto_attack.py
Labels: improvement
