Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2023-03, with the labels that each got.

#2046 Fix Incorrect Height and Width for Image Perturbations
  art/attacks/poisoning/perturbations/image_perturbations.py
  tests/attacks/poison/test_image_perturbations.py
Labels: bug, improvement

#1978 New privacy metric shapr
  art/metrics/__init__.py
  art/metrics/privacy/__init__.py
  art/metrics/privacy/membership_leakage.py
  notebooks/README.md
  notebooks/privacy_metric.ipynb
  tests/metrics/privacy/test_membership_leakage.py
Labels: enhancement

#2044 Implement Interval Bound Propagation Training
  art/defences/trainer/__init__.py
  art/defences/trainer/ibp_certified_trainer_pytorch.py
  art/defences/trainer/trainer.py
  art/estimators/certification/interval/interval.py
  art/estimators/certification/interval/pytorch.py
  art/utils.py
  docs/modules/defences/trainer.rst
  notebooks/certification_IBP_training.ipynb
  tests/estimators/certification/test_interval.py
Labels: enhancement

#2054 BadDet Regional Misclassification Attack Implementation
  art/attacks/__init__.py
  art/attacks/attack.py
  art/attacks/poisoning/__init__.py
  art/attacks/poisoning/bad_det/__init__.py
  art/attacks/poisoning/bad_det/bad_det_rma.py
  notebooks/README.md
  notebooks/poisoning_attack_bad_det_rma.ipynb
  tests/attacks/poison/bad_det/test_bad_det_rma.py
Labels: enhancement

#2063 Update supported and tested Python versions
  .github/workflows/ci-pytorch-object-detectors.yml
  .github/workflows/ci-pytorch.yml
  .github/workflows/ci-scikit-learn.yml
  .github/workflows/ci-tensorflow-v2.yml
  art/estimators/classification/scikitlearn.py
  setup.py
Labels: tests

#2053 Cache audio triggers
  art/attacks/poisoning/perturbations/audio_perturbations.py
  tests/attacks/poison/test_audio_perturbations.py
Labels: improvement

#2067 PyTorch Object Detector Training Implementation and Prediction Update
  art/estimators/object_detection/pytorch_faster_rcnn.py
  art/estimators/object_detection/pytorch_object_detector.py
  art/estimators/object_detection/pytorch_yolo.py
  notebooks/poisoning_attack_bad_det_rma.ipynb
  tests/estimators/object_detection/test_pytorch_faster_rcnn.py
  tests/estimators/object_detection/test_pytorch_object_detector.py
  tests/estimators/object_detection/test_pytorch_yolo.py
Labels: improvement

#2070 Zonotope updates 1.14
  art/defences/trainer/certified_adversarial_trainer_pytorch.py
  art/estimators/certification/deep_z/pytorch.py
Labels: improvement
