Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2023-08, with the labels that each got.

#2221 Fix errors in EoT notebook
  notebooks/expectation_over_transformation_classification_rotation.ipynb
Labels: notebooks

#2240 Make PIL an optional dependency
  art/attacks/poisoning/perturbations/image_perturbations.py
  art/visualization.py
Labels: bug, improvement

#2241 Remove circular dependency in art.estimators.certification
  art/estimators/certification/__init__.py
Labels: bug, improvement

#2249 Fix PyTorch Object Detection Estimators Missing Gradients Bug
  art/estimators/object_detection/pytorch_object_detector.py
  art/estimators/object_detection/pytorch_yolo.py
Labels: bug, improvement

#2247 Update to ART 1.15.1
  art/attacks/evasion/auto_conjugate_gradient.py
  art/attacks/evasion/auto_projected_gradient_descent.py
  art/attacks/poisoning/perturbations/image_perturbations.py
  art/defences/preprocessor/spatial_smoothing.py
  art/defences/trainer/adversarial_trainer_trades_pytorch.py
  art/estimators/certification/__init__.py
  art/estimators/object_detection/pytorch_object_detector.py
  art/estimators/object_detection/pytorch_yolo.py
  art/visualization.py
  tests/defences/trainer/test_adversarial_trainer_trades_pytorch.py
Labels: release
