Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2024-10, with the labels that each got.

#2500 Apply package.version.parse
  art/attacks/evasion/adversarial_patch/adversarial_patch_pytorch.py
  art/attacks/evasion/pixel_threshold.py
  art/estimators/object_detection/pytorch_object_detector.py
Labels: improvement

#2502 Update to ART 1.18.2
  art/attacks/evasion/adversarial_patch/adversarial_patch_pytorch.py
  art/attacks/evasion/pixel_threshold.py
  art/estimators/object_detection/pytorch_object_detector.py
Labels: release

#2460 Implement Rescaling-ACG, which is a improved version of ACG attack.
  art/attacks/evasion/__init__.py
  art/attacks/evasion/rescaling_auto_conjugate_gradient.py
  docs/modules/attacks/evasion.rst
  tests/attacks/evasion/test_rescaling_auto_conjugate_gradient.py
Labels: enhancement

#2440 Added support for SNAL attack
  art/attacks/evasion/__init__.py
  art/attacks/evasion/steal_now_attack_later/__init__.py
  art/attacks/evasion/steal_now_attack_later/bbox_ioa.py
  art/attacks/evasion/steal_now_attack_later/drop_block2d.py
  art/attacks/evasion/steal_now_attack_later/steal_now_attack_later.py
  art/estimators/object_detection/pytorch_object_detector.py
  art/estimators/object_detection/pytorch_yolo.py
  notebooks/snal.ipynb
  tests/attacks/evasion/test_steal_now_attack_later.py
Labels: enhancement
