Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2024-12, with the labels that each got.

#2534 Add option for pool size in AutoAttack
  art/attacks/evasion/auto_attack.py
  tests/attacks/evasion/test_auto_attack.py
Labels: improvement

#2505 Support sklearn models with multiple outputs
  art/estimators/classification/classifier.py
  art/utils.py
  tests/estimators/classification/test_scikitlearn.py
Labels: enhancement

#2539 Fix bug in random sampling of patch locations in masks for adversarial patch attacks
  .github/workflows/ci-pytorch-object-detectors.yml
  art/attacks/evasion/adversarial_patch/adversarial_patch_pytorch.py
  art/attacks/evasion/imperceptible_asr/imperceptible_asr_pytorch.py
  art/attacks/evasion/saliency_map.py
  art/estimators/classification/pytorch.py
  art/estimators/object_detection/pytorch_object_detector.py
  art/estimators/regression/pytorch.py
  requirements_test.txt
Labels: bug, improvement
