Repository Trusted-AI/adversarial-robustness-toolbox, pull requests merged in 2025-01, with the labels that each got.

#2550 correct f-strings in parallel/non-parallel AutoAttack metadata
  art/attacks/evasion/auto_attack.py
Labels: bug, improvement

#2558 Fix missing transfer to device in ProjectedGradientDescentPyTorch
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
Labels: bug, improvement

#2557 Improve typing and documentation of AdversarialPatchPyTorch
  art/attacks/evasion/adversarial_patch/adversarial_patch_pytorch.py
Labels: improvement, documentation

#2552 Update to ART 1.19.1
  art/attacks/evasion/adversarial_patch/adversarial_patch_pytorch.py
  art/attacks/evasion/auto_attack.py
  art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
  docs/modules/defences/detector_evasion.rst
Labels: release
